# typed: strong

module DedalusSDK
  module Models
    class CreateImageRequest < DedalusSDK::Internal::Type::BaseModel
      OrHash =
        T.type_alias do
          T.any(DedalusSDK::CreateImageRequest, DedalusSDK::Internal::AnyHash)
        end

      # A text description of the desired image(s). The maximum length is 32000
      # characters for `gpt-image-1`, 1000 characters for `dall-e-2` and 4000 characters
      # for `dall-e-3`.
      sig { returns(String) }
      attr_accessor :prompt

      # Allows to set transparency for the background of the generated image(s). This
      # parameter is only supported for `gpt-image-1`. Must be one of `transparent`,
      # `opaque` or `auto` (default value). When `auto` is used, the model will
      # automatically determine the best background for the image.
      #
      # If `transparent`, the output format needs to support transparency, so it should
      # be set to either `png` (default value) or `webp`.
      sig do
        returns(T.nilable(DedalusSDK::CreateImageRequest::Background::OrSymbol))
      end
      attr_accessor :background

      # The model to use for image generation. One of `openai/dall-e-2`,
      # `openai/dall-e-3`, or `openai/gpt-image-1`. Defaults to `openai/dall-e-2` unless
      # a parameter specific to `gpt-image-1` is used.
      sig { returns(T.nilable(String)) }
      attr_accessor :model

      # Control the content-moderation level for images generated by `gpt-image-1`. Must
      # be either `low` for less restrictive filtering or `auto` (default value).
      sig do
        returns(T.nilable(DedalusSDK::CreateImageRequest::Moderation::OrSymbol))
      end
      attr_accessor :moderation

      # The number of images to generate. Must be between 1 and 10. For `dall-e-3`, only
      # `n=1` is supported.
      sig { returns(T.nilable(Integer)) }
      attr_accessor :n

      # The compression level (0-100%) for the generated images. This parameter is only
      # supported for `gpt-image-1` with the `webp` or `jpeg` output formats, and
      # defaults to 100.
      sig { returns(T.nilable(Integer)) }
      attr_accessor :output_compression

      # The format in which the generated images are returned. This parameter is only
      # supported for `gpt-image-1`. Must be one of `png`, `jpeg`, or `webp`.
      sig do
        returns(
          T.nilable(DedalusSDK::CreateImageRequest::OutputFormat::OrSymbol)
        )
      end
      attr_accessor :output_format

      # The number of partial images to generate. This parameter is used for streaming
      # responses that return partial images. Value must be between 0 and 3. When set to
      # 0, the response will be a single image sent in one streaming event.
      #
      # Note that the final image may be sent before the full number of partial images
      # are generated if the full image is generated more quickly.
      sig { returns(T.nilable(Integer)) }
      attr_accessor :partial_images

      # The quality of the image that will be generated.
      #
      # - `auto` (default value) will automatically select the best quality for the
      #   given model.
      # - `high`, `medium` and `low` are supported for `gpt-image-1`.
      # - `hd` and `standard` are supported for `dall-e-3`.
      # - `standard` is the only option for `dall-e-2`.
      sig do
        returns(T.nilable(DedalusSDK::CreateImageRequest::Quality::OrSymbol))
      end
      attr_accessor :quality

      # The format in which generated images with `dall-e-2` and `dall-e-3` are
      # returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes
      # after the image has been generated. This parameter isn't supported for
      # `gpt-image-1` which will always return base64-encoded images.
      sig do
        returns(
          T.nilable(DedalusSDK::CreateImageRequest::ResponseFormat::OrSymbol)
        )
      end
      attr_accessor :response_format

      # The size of the generated images. Must be one of `1024x1024`, `1536x1024`
      # (landscape), `1024x1536` (portrait), or `auto` (default value) for
      # `gpt-image-1`, one of `256x256`, `512x512`, or `1024x1024` for `dall-e-2`, and
      # one of `1024x1024`, `1792x1024`, or `1024x1792` for `dall-e-3`.
      sig { returns(T.nilable(DedalusSDK::CreateImageRequest::Size::OrSymbol)) }
      attr_accessor :size

      # Generate the image in streaming mode. Defaults to `false`. See the
      # [Image generation guide](https://platform.openai.com/docs/guides/image-generation)
      # for more information. This parameter is only supported for `gpt-image-1`.
      sig { returns(T.nilable(T::Boolean)) }
      attr_accessor :stream

      # The style of the generated images. This parameter is only supported for
      # `dall-e-3`. Must be one of `vivid` or `natural`. Vivid causes the model to lean
      # towards generating hyper-real and dramatic images. Natural causes the model to
      # produce more natural, less hyper-real looking images.
      sig do
        returns(T.nilable(DedalusSDK::CreateImageRequest::Style::OrSymbol))
      end
      attr_accessor :style

      # A unique identifier representing your end-user, which can help OpenAI to monitor
      # and detect abuse.
      # [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#end-user-ids).
      sig { returns(T.nilable(String)) }
      attr_accessor :user

      # Request to generate images.
      sig do
        params(
          prompt: String,
          background:
            T.nilable(DedalusSDK::CreateImageRequest::Background::OrSymbol),
          model: T.nilable(String),
          moderation:
            T.nilable(DedalusSDK::CreateImageRequest::Moderation::OrSymbol),
          n: T.nilable(Integer),
          output_compression: T.nilable(Integer),
          output_format:
            T.nilable(DedalusSDK::CreateImageRequest::OutputFormat::OrSymbol),
          partial_images: T.nilable(Integer),
          quality: T.nilable(DedalusSDK::CreateImageRequest::Quality::OrSymbol),
          response_format:
            T.nilable(DedalusSDK::CreateImageRequest::ResponseFormat::OrSymbol),
          size: T.nilable(DedalusSDK::CreateImageRequest::Size::OrSymbol),
          stream: T.nilable(T::Boolean),
          style: T.nilable(DedalusSDK::CreateImageRequest::Style::OrSymbol),
          user: T.nilable(String)
        ).returns(T.attached_class)
      end
      def self.new(
        # A text description of the desired image(s). The maximum length is 32000
        # characters for `gpt-image-1`, 1000 characters for `dall-e-2` and 4000 characters
        # for `dall-e-3`.
        prompt:,
        # Allows to set transparency for the background of the generated image(s). This
        # parameter is only supported for `gpt-image-1`. Must be one of `transparent`,
        # `opaque` or `auto` (default value). When `auto` is used, the model will
        # automatically determine the best background for the image.
        #
        # If `transparent`, the output format needs to support transparency, so it should
        # be set to either `png` (default value) or `webp`.
        background: nil,
        # The model to use for image generation. One of `openai/dall-e-2`,
        # `openai/dall-e-3`, or `openai/gpt-image-1`. Defaults to `openai/dall-e-2` unless
        # a parameter specific to `gpt-image-1` is used.
        model: nil,
        # Control the content-moderation level for images generated by `gpt-image-1`. Must
        # be either `low` for less restrictive filtering or `auto` (default value).
        moderation: nil,
        # The number of images to generate. Must be between 1 and 10. For `dall-e-3`, only
        # `n=1` is supported.
        n: nil,
        # The compression level (0-100%) for the generated images. This parameter is only
        # supported for `gpt-image-1` with the `webp` or `jpeg` output formats, and
        # defaults to 100.
        output_compression: nil,
        # The format in which the generated images are returned. This parameter is only
        # supported for `gpt-image-1`. Must be one of `png`, `jpeg`, or `webp`.
        output_format: nil,
        # The number of partial images to generate. This parameter is used for streaming
        # responses that return partial images. Value must be between 0 and 3. When set to
        # 0, the response will be a single image sent in one streaming event.
        #
        # Note that the final image may be sent before the full number of partial images
        # are generated if the full image is generated more quickly.
        partial_images: nil,
        # The quality of the image that will be generated.
        #
        # - `auto` (default value) will automatically select the best quality for the
        #   given model.
        # - `high`, `medium` and `low` are supported for `gpt-image-1`.
        # - `hd` and `standard` are supported for `dall-e-3`.
        # - `standard` is the only option for `dall-e-2`.
        quality: nil,
        # The format in which generated images with `dall-e-2` and `dall-e-3` are
        # returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes
        # after the image has been generated. This parameter isn't supported for
        # `gpt-image-1` which will always return base64-encoded images.
        response_format: nil,
        # The size of the generated images. Must be one of `1024x1024`, `1536x1024`
        # (landscape), `1024x1536` (portrait), or `auto` (default value) for
        # `gpt-image-1`, one of `256x256`, `512x512`, or `1024x1024` for `dall-e-2`, and
        # one of `1024x1024`, `1792x1024`, or `1024x1792` for `dall-e-3`.
        size: nil,
        # Generate the image in streaming mode. Defaults to `false`. See the
        # [Image generation guide](https://platform.openai.com/docs/guides/image-generation)
        # for more information. This parameter is only supported for `gpt-image-1`.
        stream: nil,
        # The style of the generated images. This parameter is only supported for
        # `dall-e-3`. Must be one of `vivid` or `natural`. Vivid causes the model to lean
        # towards generating hyper-real and dramatic images. Natural causes the model to
        # produce more natural, less hyper-real looking images.
        style: nil,
        # A unique identifier representing your end-user, which can help OpenAI to monitor
        # and detect abuse.
        # [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#end-user-ids).
        user: nil
      )
      end

      sig do
        override.returns(
          {
            prompt: String,
            background:
              T.nilable(DedalusSDK::CreateImageRequest::Background::OrSymbol),
            model: T.nilable(String),
            moderation:
              T.nilable(DedalusSDK::CreateImageRequest::Moderation::OrSymbol),
            n: T.nilable(Integer),
            output_compression: T.nilable(Integer),
            output_format:
              T.nilable(DedalusSDK::CreateImageRequest::OutputFormat::OrSymbol),
            partial_images: T.nilable(Integer),
            quality:
              T.nilable(DedalusSDK::CreateImageRequest::Quality::OrSymbol),
            response_format:
              T.nilable(
                DedalusSDK::CreateImageRequest::ResponseFormat::OrSymbol
              ),
            size: T.nilable(DedalusSDK::CreateImageRequest::Size::OrSymbol),
            stream: T.nilable(T::Boolean),
            style: T.nilable(DedalusSDK::CreateImageRequest::Style::OrSymbol),
            user: T.nilable(String)
          }
        )
      end
      def to_hash
      end

      # Allows to set transparency for the background of the generated image(s). This
      # parameter is only supported for `gpt-image-1`. Must be one of `transparent`,
      # `opaque` or `auto` (default value). When `auto` is used, the model will
      # automatically determine the best background for the image.
      #
      # If `transparent`, the output format needs to support transparency, so it should
      # be set to either `png` (default value) or `webp`.
      module Background
        extend DedalusSDK::Internal::Type::Enum

        TaggedSymbol =
          T.type_alias do
            T.all(Symbol, DedalusSDK::CreateImageRequest::Background)
          end
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        TRANSPARENT =
          T.let(
            :transparent,
            DedalusSDK::CreateImageRequest::Background::TaggedSymbol
          )
        OPAQUE =
          T.let(
            :opaque,
            DedalusSDK::CreateImageRequest::Background::TaggedSymbol
          )
        AUTO =
          T.let(:auto, DedalusSDK::CreateImageRequest::Background::TaggedSymbol)

        sig do
          override.returns(
            T::Array[DedalusSDK::CreateImageRequest::Background::TaggedSymbol]
          )
        end
        def self.values
        end
      end

      # Control the content-moderation level for images generated by `gpt-image-1`. Must
      # be either `low` for less restrictive filtering or `auto` (default value).
      module Moderation
        extend DedalusSDK::Internal::Type::Enum

        TaggedSymbol =
          T.type_alias do
            T.all(Symbol, DedalusSDK::CreateImageRequest::Moderation)
          end
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        LOW =
          T.let(:low, DedalusSDK::CreateImageRequest::Moderation::TaggedSymbol)
        AUTO =
          T.let(:auto, DedalusSDK::CreateImageRequest::Moderation::TaggedSymbol)

        sig do
          override.returns(
            T::Array[DedalusSDK::CreateImageRequest::Moderation::TaggedSymbol]
          )
        end
        def self.values
        end
      end

      # The format in which the generated images are returned. This parameter is only
      # supported for `gpt-image-1`. Must be one of `png`, `jpeg`, or `webp`.
      module OutputFormat
        extend DedalusSDK::Internal::Type::Enum

        TaggedSymbol =
          T.type_alias do
            T.all(Symbol, DedalusSDK::CreateImageRequest::OutputFormat)
          end
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        PNG =
          T.let(
            :png,
            DedalusSDK::CreateImageRequest::OutputFormat::TaggedSymbol
          )
        JPEG =
          T.let(
            :jpeg,
            DedalusSDK::CreateImageRequest::OutputFormat::TaggedSymbol
          )
        WEBP =
          T.let(
            :webp,
            DedalusSDK::CreateImageRequest::OutputFormat::TaggedSymbol
          )

        sig do
          override.returns(
            T::Array[DedalusSDK::CreateImageRequest::OutputFormat::TaggedSymbol]
          )
        end
        def self.values
        end
      end

      # The quality of the image that will be generated.
      #
      # - `auto` (default value) will automatically select the best quality for the
      #   given model.
      # - `high`, `medium` and `low` are supported for `gpt-image-1`.
      # - `hd` and `standard` are supported for `dall-e-3`.
      # - `standard` is the only option for `dall-e-2`.
      module Quality
        extend DedalusSDK::Internal::Type::Enum

        TaggedSymbol =
          T.type_alias do
            T.all(Symbol, DedalusSDK::CreateImageRequest::Quality)
          end
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        AUTO =
          T.let(:auto, DedalusSDK::CreateImageRequest::Quality::TaggedSymbol)
        HIGH =
          T.let(:high, DedalusSDK::CreateImageRequest::Quality::TaggedSymbol)
        MEDIUM =
          T.let(:medium, DedalusSDK::CreateImageRequest::Quality::TaggedSymbol)
        LOW = T.let(:low, DedalusSDK::CreateImageRequest::Quality::TaggedSymbol)
        HD = T.let(:hd, DedalusSDK::CreateImageRequest::Quality::TaggedSymbol)
        STANDARD =
          T.let(
            :standard,
            DedalusSDK::CreateImageRequest::Quality::TaggedSymbol
          )

        sig do
          override.returns(
            T::Array[DedalusSDK::CreateImageRequest::Quality::TaggedSymbol]
          )
        end
        def self.values
        end
      end

      # The format in which generated images with `dall-e-2` and `dall-e-3` are
      # returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes
      # after the image has been generated. This parameter isn't supported for
      # `gpt-image-1` which will always return base64-encoded images.
      module ResponseFormat
        extend DedalusSDK::Internal::Type::Enum

        TaggedSymbol =
          T.type_alias do
            T.all(Symbol, DedalusSDK::CreateImageRequest::ResponseFormat)
          end
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        URL =
          T.let(
            :url,
            DedalusSDK::CreateImageRequest::ResponseFormat::TaggedSymbol
          )
        B64_JSON =
          T.let(
            :b64_json,
            DedalusSDK::CreateImageRequest::ResponseFormat::TaggedSymbol
          )

        sig do
          override.returns(
            T::Array[
              DedalusSDK::CreateImageRequest::ResponseFormat::TaggedSymbol
            ]
          )
        end
        def self.values
        end
      end

      # The size of the generated images. Must be one of `1024x1024`, `1536x1024`
      # (landscape), `1024x1536` (portrait), or `auto` (default value) for
      # `gpt-image-1`, one of `256x256`, `512x512`, or `1024x1024` for `dall-e-2`, and
      # one of `1024x1024`, `1792x1024`, or `1024x1792` for `dall-e-3`.
      module Size
        extend DedalusSDK::Internal::Type::Enum

        TaggedSymbol =
          T.type_alias { T.all(Symbol, DedalusSDK::CreateImageRequest::Size) }
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        SIZE_256X256 =
          T.let(:"256x256", DedalusSDK::CreateImageRequest::Size::TaggedSymbol)
        SIZE_512X512 =
          T.let(:"512x512", DedalusSDK::CreateImageRequest::Size::TaggedSymbol)
        SIZE_1024X1024 =
          T.let(
            :"1024x1024",
            DedalusSDK::CreateImageRequest::Size::TaggedSymbol
          )
        SIZE_1536X1024 =
          T.let(
            :"1536x1024",
            DedalusSDK::CreateImageRequest::Size::TaggedSymbol
          )
        SIZE_1024X1536 =
          T.let(
            :"1024x1536",
            DedalusSDK::CreateImageRequest::Size::TaggedSymbol
          )
        SIZE_1792X1024 =
          T.let(
            :"1792x1024",
            DedalusSDK::CreateImageRequest::Size::TaggedSymbol
          )
        SIZE_1024X1792 =
          T.let(
            :"1024x1792",
            DedalusSDK::CreateImageRequest::Size::TaggedSymbol
          )
        AUTO = T.let(:auto, DedalusSDK::CreateImageRequest::Size::TaggedSymbol)

        sig do
          override.returns(
            T::Array[DedalusSDK::CreateImageRequest::Size::TaggedSymbol]
          )
        end
        def self.values
        end
      end

      # The style of the generated images. This parameter is only supported for
      # `dall-e-3`. Must be one of `vivid` or `natural`. Vivid causes the model to lean
      # towards generating hyper-real and dramatic images. Natural causes the model to
      # produce more natural, less hyper-real looking images.
      module Style
        extend DedalusSDK::Internal::Type::Enum

        TaggedSymbol =
          T.type_alias { T.all(Symbol, DedalusSDK::CreateImageRequest::Style) }
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        VIVID =
          T.let(:vivid, DedalusSDK::CreateImageRequest::Style::TaggedSymbol)
        NATURAL =
          T.let(:natural, DedalusSDK::CreateImageRequest::Style::TaggedSymbol)

        sig do
          override.returns(
            T::Array[DedalusSDK::CreateImageRequest::Style::TaggedSymbol]
          )
        end
        def self.values
        end
      end
    end
  end
end
