# typed: strong

module DedalusSDK
  module Models
    class CreateEmbeddingResponse < DedalusSDK::Internal::Type::BaseModel
      OrHash =
        T.type_alias do
          T.any(
            DedalusSDK::CreateEmbeddingResponse,
            DedalusSDK::Internal::AnyHash
          )
        end

      # The list of embeddings generated by the model.
      sig { returns(T::Array[DedalusSDK::CreateEmbeddingResponse::Data]) }
      attr_accessor :data

      # The name of the model used to generate the embedding.
      sig { returns(String) }
      attr_accessor :model

      # The object type, which is always "list".
      sig { returns(Symbol) }
      attr_accessor :object

      # The usage information for the request.
      sig { returns(DedalusSDK::CreateEmbeddingResponse::Usage) }
      attr_reader :usage

      sig do
        params(usage: DedalusSDK::CreateEmbeddingResponse::Usage::OrHash).void
      end
      attr_writer :usage

      # Schema for EmbeddingResponse.
      #
      # Fields:
      #
      # - data (required): list[Embedding]
      # - model (required): str
      # - object (required): Literal["list"]
      # - usage (required): Usage
      sig do
        params(
          data: T::Array[DedalusSDK::CreateEmbeddingResponse::Data::OrHash],
          model: String,
          usage: DedalusSDK::CreateEmbeddingResponse::Usage::OrHash,
          object: Symbol
        ).returns(T.attached_class)
      end
      def self.new(
        # The list of embeddings generated by the model.
        data:,
        # The name of the model used to generate the embedding.
        model:,
        # The usage information for the request.
        usage:,
        # The object type, which is always "list".
        object: :list
      )
      end

      sig do
        override.returns(
          {
            data: T::Array[DedalusSDK::CreateEmbeddingResponse::Data],
            model: String,
            object: Symbol,
            usage: DedalusSDK::CreateEmbeddingResponse::Usage
          }
        )
      end
      def to_hash
      end

      class Data < DedalusSDK::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              DedalusSDK::CreateEmbeddingResponse::Data,
              DedalusSDK::Internal::AnyHash
            )
          end

        # The embedding vector, which is a list of floats. The length of vector depends on
        # the model as listed in the [embedding guide](/docs/guides/embeddings).
        sig { returns(T::Array[Float]) }
        attr_accessor :embedding

        # The index of the embedding in the list of embeddings.
        sig { returns(Integer) }
        attr_accessor :index

        # The object type, which is always "embedding".
        sig { returns(Symbol) }
        attr_accessor :object

        # Represents an embedding vector returned by embedding endpoint.
        #
        # Fields:
        #
        # - index (required): int
        # - embedding (required): list[float]
        # - object (required): Literal["embedding"]
        sig do
          params(
            embedding: T::Array[Float],
            index: Integer,
            object: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The embedding vector, which is a list of floats. The length of vector depends on
          # the model as listed in the [embedding guide](/docs/guides/embeddings).
          embedding:,
          # The index of the embedding in the list of embeddings.
          index:,
          # The object type, which is always "embedding".
          object: :embedding
        )
        end

        sig do
          override.returns(
            { embedding: T::Array[Float], index: Integer, object: Symbol }
          )
        end
        def to_hash
        end
      end

      class Usage < DedalusSDK::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              DedalusSDK::CreateEmbeddingResponse::Usage,
              DedalusSDK::Internal::AnyHash
            )
          end

        # The number of tokens used by the prompt.
        sig { returns(Integer) }
        attr_accessor :prompt_tokens

        # The total number of tokens used by the request.
        sig { returns(Integer) }
        attr_accessor :total_tokens

        # The usage information for the request.
        sig do
          params(prompt_tokens: Integer, total_tokens: Integer).returns(
            T.attached_class
          )
        end
        def self.new(
          # The number of tokens used by the prompt.
          prompt_tokens:,
          # The total number of tokens used by the request.
          total_tokens:
        )
        end

        sig do
          override.returns({ prompt_tokens: Integer, total_tokens: Integer })
        end
        def to_hash
        end
      end
    end
  end
end
