# typed: strong

module DedalusSDK
  module Models
    class Response < DedalusSDK::Internal::Type::BaseModel
      OrHash =
        T.type_alias do
          T.any(DedalusSDK::Response, DedalusSDK::Internal::AnyHash)
        end

      # Unique identifier for this Response
      sig { returns(String) }
      attr_accessor :id

      # Unix timestamp (in seconds) when this Response was created
      sig { returns(Float) }
      attr_accessor :created_at

      # The model used for this response
      sig { returns(String) }
      attr_accessor :model

      # Array of content items generated by the model
      sig do
        returns(
          T::Array[
            T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
          ]
        )
      end
      attr_accessor :output

      # The status of the response generation
      sig { returns(DedalusSDK::Response::Status::TaggedSymbol) }
      attr_accessor :status

      # Whether the request was run in the background
      sig { returns(T.nilable(T::Boolean)) }
      attr_accessor :background

      # Unix timestamp (in seconds) when the response was completed
      sig { returns(T.nilable(Float)) }
      attr_accessor :completed_at

      # Conversation this response belongs to (requires BYOK)
      sig do
        returns(
          T.nilable(
            T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
          )
        )
      end
      attr_accessor :conversation

      # Error details if status is 'failed'
      sig do
        returns(
          T.nilable(
            T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
          )
        )
      end
      attr_accessor :error

      # Frequency penalty used for this response
      sig { returns(T.nilable(Float)) }
      attr_accessor :frequency_penalty

      # Details about why the response is incomplete (e.g., max_output_tokens,
      # content_filter)
      sig { returns(T.nilable(T::Hash[Symbol, String])) }
      attr_accessor :incomplete_details

      # System/developer instructions used
      sig { returns(T.nilable(DedalusSDK::Response::Instructions::Variants)) }
      attr_accessor :instructions

      # Maximum output tokens allowed for this response
      sig { returns(T.nilable(Integer)) }
      attr_accessor :max_output_tokens

      # Maximum tool calls allowed for this response
      sig { returns(T.nilable(Integer)) }
      attr_accessor :max_tool_calls

      # MCP server failures keyed by server name.
      sig do
        returns(
          T.nilable(T::Hash[Symbol, DedalusSDK::Response::MCPServerError])
        )
      end
      attr_accessor :mcp_server_errors

      # Results of MCP tool executions including inputs, outputs, and timing.
      sig { returns(T.nilable(T::Array[DedalusSDK::MCPToolResult])) }
      attr_accessor :mcp_tool_results

      # Key-value pairs attached to this response (requires BYOK)
      sig { returns(T.nilable(T::Hash[Symbol, String])) }
      attr_accessor :metadata

      # The object type, always 'response'
      sig { returns(T.nilable(DedalusSDK::Response::Object::TaggedSymbol)) }
      attr_reader :object

      sig { params(object: DedalusSDK::Response::Object::OrSymbol).void }
      attr_writer :object

      # Aggregated text output from all output_text items (SDK-only convenience
      # property)
      sig { returns(T.nilable(String)) }
      attr_accessor :output_text

      # Whether parallel tool calls were enabled
      sig { returns(T.nilable(T::Boolean)) }
      attr_accessor :parallel_tool_calls

      # Presence penalty used for this response
      sig { returns(T.nilable(Float)) }
      attr_accessor :presence_penalty

      # Previous response ID referenced, if any
      sig { returns(T.nilable(String)) }
      attr_accessor :previous_response_id

      # Prompt cache key used for this response
      sig { returns(T.nilable(String)) }
      attr_accessor :prompt_cache_key

      # Reasoning configuration and outputs
      sig do
        returns(
          T.nilable(
            T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
          )
        )
      end
      attr_accessor :reasoning

      # Safety identifier used for this response
      sig { returns(T.nilable(String)) }
      attr_accessor :safety_identifier

      # Service tier used for this response
      sig { returns(T.nilable(String)) }
      attr_accessor :service_tier

      # Whether the response was stored for later retrieval
      sig { returns(T.nilable(T::Boolean)) }
      attr_accessor :store

      # Temperature parameter used
      sig { returns(T.nilable(Float)) }
      attr_accessor :temperature

      # Text configuration used for this response
      sig do
        returns(
          T.nilable(
            T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
          )
        )
      end
      attr_accessor :text

      # Tool choice configuration used
      sig { returns(T.nilable(DedalusSDK::Response::ToolChoice::Variants)) }
      attr_accessor :tool_choice

      # Tools that were available to the model
      sig do
        returns(
          T.nilable(
            T::Array[
              T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
            ]
          )
        )
      end
      attr_accessor :tools

      # List of tool names that were executed server-side (e.g., MCP tools).
      sig { returns(T.nilable(T::Array[String])) }
      attr_accessor :tools_executed

      # Number of logprob tokens returned per position
      sig { returns(T.nilable(Integer)) }
      attr_accessor :top_logprobs

      # Top-p parameter used
      sig { returns(T.nilable(Float)) }
      attr_accessor :top_p

      # Truncation strategy applied when context exceeded limits
      sig { returns(T.nilable(String)) }
      attr_accessor :truncation

      # Token usage statistics for the response
      sig do
        returns(
          T.nilable(
            T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
          )
        )
      end
      attr_accessor :usage

      # Responses API response with Dedalus extensions.
      sig do
        params(
          id: String,
          created_at: Float,
          model: String,
          output:
            T::Array[
              T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
            ],
          status: DedalusSDK::Response::Status::OrSymbol,
          background: T.nilable(T::Boolean),
          completed_at: T.nilable(Float),
          conversation:
            T.nilable(
              T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
            ),
          error:
            T.nilable(
              T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
            ),
          frequency_penalty: T.nilable(Float),
          incomplete_details: T.nilable(T::Hash[Symbol, String]),
          instructions: T.nilable(DedalusSDK::Response::Instructions::Variants),
          max_output_tokens: T.nilable(Integer),
          max_tool_calls: T.nilable(Integer),
          mcp_server_errors:
            T.nilable(
              T::Hash[Symbol, DedalusSDK::Response::MCPServerError::OrHash]
            ),
          mcp_tool_results:
            T.nilable(T::Array[DedalusSDK::MCPToolResult::OrHash]),
          metadata: T.nilable(T::Hash[Symbol, String]),
          object: DedalusSDK::Response::Object::OrSymbol,
          output_text: T.nilable(String),
          parallel_tool_calls: T.nilable(T::Boolean),
          presence_penalty: T.nilable(Float),
          previous_response_id: T.nilable(String),
          prompt_cache_key: T.nilable(String),
          reasoning:
            T.nilable(
              T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
            ),
          safety_identifier: T.nilable(String),
          service_tier: T.nilable(String),
          store: T.nilable(T::Boolean),
          temperature: T.nilable(Float),
          text:
            T.nilable(
              T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
            ),
          tool_choice: T.nilable(DedalusSDK::Response::ToolChoice::Variants),
          tools:
            T.nilable(
              T::Array[
                T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
              ]
            ),
          tools_executed: T.nilable(T::Array[String]),
          top_logprobs: T.nilable(Integer),
          top_p: T.nilable(Float),
          truncation: T.nilable(String),
          usage:
            T.nilable(
              T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
            )
        ).returns(T.attached_class)
      end
      def self.new(
        # Unique identifier for this Response
        id:,
        # Unix timestamp (in seconds) when this Response was created
        created_at:,
        # The model used for this response
        model:,
        # Array of content items generated by the model
        output:,
        # The status of the response generation
        status:,
        # Whether the request was run in the background
        background: nil,
        # Unix timestamp (in seconds) when the response was completed
        completed_at: nil,
        # Conversation this response belongs to (requires BYOK)
        conversation: nil,
        # Error details if status is 'failed'
        error: nil,
        # Frequency penalty used for this response
        frequency_penalty: nil,
        # Details about why the response is incomplete (e.g., max_output_tokens,
        # content_filter)
        incomplete_details: nil,
        # System/developer instructions used
        instructions: nil,
        # Maximum output tokens allowed for this response
        max_output_tokens: nil,
        # Maximum tool calls allowed for this response
        max_tool_calls: nil,
        # MCP server failures keyed by server name.
        mcp_server_errors: nil,
        # Results of MCP tool executions including inputs, outputs, and timing.
        mcp_tool_results: nil,
        # Key-value pairs attached to this response (requires BYOK)
        metadata: nil,
        # The object type, always 'response'
        object: nil,
        # Aggregated text output from all output_text items (SDK-only convenience
        # property)
        output_text: nil,
        # Whether parallel tool calls were enabled
        parallel_tool_calls: nil,
        # Presence penalty used for this response
        presence_penalty: nil,
        # Previous response ID referenced, if any
        previous_response_id: nil,
        # Prompt cache key used for this response
        prompt_cache_key: nil,
        # Reasoning configuration and outputs
        reasoning: nil,
        # Safety identifier used for this response
        safety_identifier: nil,
        # Service tier used for this response
        service_tier: nil,
        # Whether the response was stored for later retrieval
        store: nil,
        # Temperature parameter used
        temperature: nil,
        # Text configuration used for this response
        text: nil,
        # Tool choice configuration used
        tool_choice: nil,
        # Tools that were available to the model
        tools: nil,
        # List of tool names that were executed server-side (e.g., MCP tools).
        tools_executed: nil,
        # Number of logprob tokens returned per position
        top_logprobs: nil,
        # Top-p parameter used
        top_p: nil,
        # Truncation strategy applied when context exceeded limits
        truncation: nil,
        # Token usage statistics for the response
        usage: nil
      )
      end

      sig do
        override.returns(
          {
            id: String,
            created_at: Float,
            model: String,
            output:
              T::Array[
                T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
              ],
            status: DedalusSDK::Response::Status::TaggedSymbol,
            background: T.nilable(T::Boolean),
            completed_at: T.nilable(Float),
            conversation:
              T.nilable(
                T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
              ),
            error:
              T.nilable(
                T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
              ),
            frequency_penalty: T.nilable(Float),
            incomplete_details: T.nilable(T::Hash[Symbol, String]),
            instructions:
              T.nilable(DedalusSDK::Response::Instructions::Variants),
            max_output_tokens: T.nilable(Integer),
            max_tool_calls: T.nilable(Integer),
            mcp_server_errors:
              T.nilable(T::Hash[Symbol, DedalusSDK::Response::MCPServerError]),
            mcp_tool_results: T.nilable(T::Array[DedalusSDK::MCPToolResult]),
            metadata: T.nilable(T::Hash[Symbol, String]),
            object: DedalusSDK::Response::Object::TaggedSymbol,
            output_text: T.nilable(String),
            parallel_tool_calls: T.nilable(T::Boolean),
            presence_penalty: T.nilable(Float),
            previous_response_id: T.nilable(String),
            prompt_cache_key: T.nilable(String),
            reasoning:
              T.nilable(
                T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
              ),
            safety_identifier: T.nilable(String),
            service_tier: T.nilable(String),
            store: T.nilable(T::Boolean),
            temperature: T.nilable(Float),
            text:
              T.nilable(
                T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
              ),
            tool_choice: T.nilable(DedalusSDK::Response::ToolChoice::Variants),
            tools:
              T.nilable(
                T::Array[
                  T::Hash[
                    Symbol,
                    T.nilable(DedalusSDK::JSONValueInput::Variants)
                  ]
                ]
              ),
            tools_executed: T.nilable(T::Array[String]),
            top_logprobs: T.nilable(Integer),
            top_p: T.nilable(Float),
            truncation: T.nilable(String),
            usage:
              T.nilable(
                T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
              )
          }
        )
      end
      def to_hash
      end

      # The status of the response generation
      module Status
        extend DedalusSDK::Internal::Type::Enum

        TaggedSymbol =
          T.type_alias { T.all(Symbol, DedalusSDK::Response::Status) }
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        COMPLETED =
          T.let(:completed, DedalusSDK::Response::Status::TaggedSymbol)
        FAILED = T.let(:failed, DedalusSDK::Response::Status::TaggedSymbol)
        IN_PROGRESS =
          T.let(:in_progress, DedalusSDK::Response::Status::TaggedSymbol)
        CANCELLED =
          T.let(:cancelled, DedalusSDK::Response::Status::TaggedSymbol)
        QUEUED = T.let(:queued, DedalusSDK::Response::Status::TaggedSymbol)
        INCOMPLETE =
          T.let(:incomplete, DedalusSDK::Response::Status::TaggedSymbol)

        sig do
          override.returns(T::Array[DedalusSDK::Response::Status::TaggedSymbol])
        end
        def self.values
        end
      end

      # System/developer instructions used
      module Instructions
        extend DedalusSDK::Internal::Type::Union

        Variants =
          T.type_alias do
            T.any(
              String,
              T::Array[
                T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
              ]
            )
          end

        sig do
          override.returns(
            T::Array[DedalusSDK::Response::Instructions::Variants]
          )
        end
        def self.variants
        end

        JSONObjectInputArray =
          T.let(
            DedalusSDK::Internal::Type::ArrayOf[
              DedalusSDK::Internal::Type::HashOf[
                union: DedalusSDK::JSONValueInput,
                nil?: true
              ]
            ],
            DedalusSDK::Internal::Type::Converter
          )
      end

      class MCPServerError < DedalusSDK::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              DedalusSDK::Response::MCPServerError,
              DedalusSDK::Internal::AnyHash
            )
          end

        # Human-readable error message.
        sig { returns(String) }
        attr_accessor :message

        # Machine-readable error code.
        sig { returns(T.nilable(String)) }
        attr_accessor :code

        # Suggested action for the user.
        sig { returns(T.nilable(String)) }
        attr_accessor :recommendation

        # Error details for a single MCP server failure.
        sig do
          params(
            message: String,
            code: T.nilable(String),
            recommendation: T.nilable(String)
          ).returns(T.attached_class)
        end
        def self.new(
          # Human-readable error message.
          message:,
          # Machine-readable error code.
          code: nil,
          # Suggested action for the user.
          recommendation: nil
        )
        end

        sig do
          override.returns(
            {
              message: String,
              code: T.nilable(String),
              recommendation: T.nilable(String)
            }
          )
        end
        def to_hash
        end
      end

      # The object type, always 'response'
      module Object
        extend DedalusSDK::Internal::Type::Enum

        TaggedSymbol =
          T.type_alias { T.all(Symbol, DedalusSDK::Response::Object) }
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        RESPONSE = T.let(:response, DedalusSDK::Response::Object::TaggedSymbol)

        sig do
          override.returns(T::Array[DedalusSDK::Response::Object::TaggedSymbol])
        end
        def self.values
        end
      end

      # Tool choice configuration used
      module ToolChoice
        extend DedalusSDK::Internal::Type::Union

        Variants =
          T.type_alias do
            T.any(
              String,
              T::Hash[Symbol, T.nilable(DedalusSDK::JSONValueInput::Variants)]
            )
          end

        sig do
          override.returns(T::Array[DedalusSDK::Response::ToolChoice::Variants])
        end
        def self.variants
        end
      end
    end
  end
end
