module DedalusSDK
  module Models
    type credential =
      {
        connection_name: String,
        values: ::Hash[Symbol, DedalusSDK::Models::Credential::value]
      }

    class Credential < DedalusSDK::Internal::Type::BaseModel
      attr_accessor connection_name: String

      attr_accessor values: ::Hash[Symbol, DedalusSDK::Models::Credential::value]

      def initialize: (
        connection_name: String,
        values: ::Hash[Symbol, DedalusSDK::Models::Credential::value]
      ) -> void

      def to_hash: -> {
        connection_name: String,
        values: ::Hash[Symbol, DedalusSDK::Models::Credential::value]
      }

      type value = String | Integer | bool

      module Value
        extend DedalusSDK::Internal::Type::Union

        def self?.variants: -> ::Array[DedalusSDK::Models::Credential::value]
      end
    end
  end
end
