module DedalusSDK
  module Models
    type image_generate_params =
      {  } & DedalusSDK::Internal::Type::request_parameters

    class ImageGenerateParams < DedalusSDK::Models::CreateImageRequest
      extend DedalusSDK::Internal::Type::RequestParameters::Converter
      include DedalusSDK::Internal::Type::RequestParameters

      def initialize: (?request_options: DedalusSDK::request_opts) -> void

      def to_hash: -> { request_options: DedalusSDK::RequestOptions }
    end
  end
end
