module DedalusSDK
  module Models
    type mcp_server_spec =
      {
        name: String,
        credentials: ::Hash[Symbol, String]?,
        slug: String?,
        url: String?,
        version: String?
      }

    class MCPServerSpec < DedalusSDK::Internal::Type::BaseModel
      attr_accessor name: String

      attr_accessor credentials: ::Hash[Symbol, String]?

      attr_accessor slug: String?

      attr_accessor url: String?

      attr_accessor version: String?

      def initialize: (
        name: String,
        ?credentials: ::Hash[Symbol, String]?,
        ?slug: String?,
        ?url: String?,
        ?version: String?
      ) -> void

      def to_hash: -> {
        name: String,
        credentials: ::Hash[Symbol, String]?,
        slug: String?,
        url: String?,
        version: String?
      }
    end
  end
end
