module DedalusSDK
  module Models
    type ocr_page = { index: Integer, markdown: String }

    class OCRPage < DedalusSDK::Internal::Type::BaseModel
      attr_accessor index: Integer

      attr_accessor markdown: String

      def initialize: (index: Integer, markdown: String) -> void

      def to_hash: -> { index: Integer, markdown: String }
    end
  end
end
