module DedalusSDK
  module Models
    type voice_ids_or_custom_voice = { id: String }

    class VoiceIDsOrCustomVoice < DedalusSDK::Internal::Type::BaseModel
      attr_accessor id: String

      def initialize: (id: String) -> void

      def to_hash: -> { id: String }
    end
  end
end
