module DedalusSDK
  module Resources
    class Chat
      class Completions
        def create: (
          model: DedalusSDK::Models::Chat::ChatCompletionCreateParams::model,
          ?agent_attributes: ::Hash[Symbol, Float]?,
          ?audio: DedalusSDK::Chat::ChatCompletionAudioParam?,
          ?automatic_tool_execution: bool,
          ?cached_content: String?,
          ?correlation_id: String?,
          ?credentials: DedalusSDK::Models::Chat::ChatCompletionCreateParams::credentials?,
          ?deferred: bool?,
          ?deferred_calls: ::Array[DedalusSDK::Chat::DeferredCallResponse]?,
          ?frequency_penalty: Float?,
          ?function_call: String?,
          ?functions: ::Array[DedalusSDK::Chat::ChatCompletionFunctions]?,
          ?generation_config: DedalusSDK::Models::json_object_input?,
          ?guardrails: ::Array[::Hash[Symbol, top]]?,
          ?handoff_config: ::Hash[Symbol, top]?,
          ?handoff_mode: bool?,
          ?inference_geo: String?,
          ?logit_bias: ::Hash[Symbol, Integer]?,
          ?logprobs: bool?,
          ?max_completion_tokens: Integer?,
          ?max_tokens: Integer?,
          ?max_turns: Integer?,
          ?mcp_servers: DedalusSDK::Models::Chat::ChatCompletionCreateParams::mcp_servers?,
          ?messages: ::Array[DedalusSDK::Models::Chat::ChatCompletionCreateParams::message]?,
          ?metadata: DedalusSDK::Models::json_object_input?,
          ?modalities: ::Array[String]?,
          ?model_attributes: ::Hash[Symbol, ::Hash[Symbol, Float]]?,
          ?n: Integer?,
          ?output_config: DedalusSDK::Models::json_object_input?,
          ?parallel_tool_calls: bool?,
          ?prediction: DedalusSDK::Chat::PredictionContent?,
          ?presence_penalty: Float?,
          ?prompt_cache_key: String?,
          ?prompt_cache_retention: String?,
          ?prompt_mode: DedalusSDK::Models::Chat::ChatCompletionCreateParams::prompt_mode?,
          ?reasoning_effort: String?,
          ?response_format: DedalusSDK::Models::Chat::ChatCompletionCreateParams::response_format?,
          ?safe_prompt: bool?,
          ?safety_identifier: String?,
          ?safety_settings: ::Array[DedalusSDK::Chat::ChatCompletionCreateParams::SafetySetting]?,
          ?search_parameters: DedalusSDK::Models::json_object_input?,
          ?seed: Integer?,
          ?service_tier: String?,
          ?speed: DedalusSDK::Models::Chat::ChatCompletionCreateParams::speed?,
          ?stop: DedalusSDK::Models::Chat::ChatCompletionCreateParams::stop?,
          ?store: bool?,
          ?stream_options: DedalusSDK::Models::json_object_input?,
          ?system_instruction: DedalusSDK::Models::Chat::ChatCompletionCreateParams::system_instruction?,
          ?temperature: Float?,
          ?thinking: DedalusSDK::Models::Chat::ChatCompletionCreateParams::thinking?,
          ?tool_choice: DedalusSDK::Models::Chat::ChatCompletionCreateParams::tool_choice?,
          ?tool_config: DedalusSDK::Models::json_object_input?,
          ?tools: ::Array[DedalusSDK::Chat::ChatCompletionToolParam]?,
          ?top_k: Integer?,
          ?top_logprobs: Integer?,
          ?top_p: Float?,
          ?user: String?,
          ?verbosity: String?,
          ?web_search_options: DedalusSDK::Models::json_object_input?,
          ?request_options: DedalusSDK::request_opts
        ) -> DedalusSDK::Chat::ChatCompletion

        def create_streaming: (
          model: DedalusSDK::Models::Chat::ChatCompletionCreateParams::model,
          ?agent_attributes: ::Hash[Symbol, Float]?,
          ?audio: DedalusSDK::Chat::ChatCompletionAudioParam?,
          ?automatic_tool_execution: bool,
          ?cached_content: String?,
          ?correlation_id: String?,
          ?credentials: DedalusSDK::Models::Chat::ChatCompletionCreateParams::credentials?,
          ?deferred: bool?,
          ?deferred_calls: ::Array[DedalusSDK::Chat::DeferredCallResponse]?,
          ?frequency_penalty: Float?,
          ?function_call: String?,
          ?functions: ::Array[DedalusSDK::Chat::ChatCompletionFunctions]?,
          ?generation_config: DedalusSDK::Models::json_object_input?,
          ?guardrails: ::Array[::Hash[Symbol, top]]?,
          ?handoff_config: ::Hash[Symbol, top]?,
          ?handoff_mode: bool?,
          ?inference_geo: String?,
          ?logit_bias: ::Hash[Symbol, Integer]?,
          ?logprobs: bool?,
          ?max_completion_tokens: Integer?,
          ?max_tokens: Integer?,
          ?max_turns: Integer?,
          ?mcp_servers: DedalusSDK::Models::Chat::ChatCompletionCreateParams::mcp_servers?,
          ?messages: ::Array[DedalusSDK::Models::Chat::ChatCompletionCreateParams::message]?,
          ?metadata: DedalusSDK::Models::json_object_input?,
          ?modalities: ::Array[String]?,
          ?model_attributes: ::Hash[Symbol, ::Hash[Symbol, Float]]?,
          ?n: Integer?,
          ?output_config: DedalusSDK::Models::json_object_input?,
          ?parallel_tool_calls: bool?,
          ?prediction: DedalusSDK::Chat::PredictionContent?,
          ?presence_penalty: Float?,
          ?prompt_cache_key: String?,
          ?prompt_cache_retention: String?,
          ?prompt_mode: DedalusSDK::Models::Chat::ChatCompletionCreateParams::prompt_mode?,
          ?reasoning_effort: String?,
          ?response_format: DedalusSDK::Models::Chat::ChatCompletionCreateParams::response_format?,
          ?safe_prompt: bool?,
          ?safety_identifier: String?,
          ?safety_settings: ::Array[DedalusSDK::Chat::ChatCompletionCreateParams::SafetySetting]?,
          ?search_parameters: DedalusSDK::Models::json_object_input?,
          ?seed: Integer?,
          ?service_tier: String?,
          ?speed: DedalusSDK::Models::Chat::ChatCompletionCreateParams::speed?,
          ?stop: DedalusSDK::Models::Chat::ChatCompletionCreateParams::stop?,
          ?store: bool?,
          ?stream_options: DedalusSDK::Models::json_object_input?,
          ?system_instruction: DedalusSDK::Models::Chat::ChatCompletionCreateParams::system_instruction?,
          ?temperature: Float?,
          ?thinking: DedalusSDK::Models::Chat::ChatCompletionCreateParams::thinking?,
          ?tool_choice: DedalusSDK::Models::Chat::ChatCompletionCreateParams::tool_choice?,
          ?tool_config: DedalusSDK::Models::json_object_input?,
          ?tools: ::Array[DedalusSDK::Chat::ChatCompletionToolParam]?,
          ?top_k: Integer?,
          ?top_logprobs: Integer?,
          ?top_p: Float?,
          ?user: String?,
          ?verbosity: String?,
          ?web_search_options: DedalusSDK::Models::json_object_input?,
          ?request_options: DedalusSDK::request_opts
        ) -> DedalusSDK::Internal::Stream[DedalusSDK::Chat::ChatCompletionChunk]

        def initialize: (client: DedalusSDK::Client) -> void
      end
    end
  end
end
