module DedalusSDK
  module Models
    module Chat
      type audio = { id: String }

      class Audio < DedalusSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end
    end
  end
end
