module DedalusSDK
  module Models
    class ChatCompletionToolMessageParam = Chat::ChatCompletionToolMessageParam

    module Chat
      type chat_completion_tool_message_param =
        {
          content: DedalusSDK::Models::Chat::ChatCompletionToolMessageParam::content,
          role: :tool,
          tool_call_id: String
        }

      class ChatCompletionToolMessageParam < DedalusSDK::Internal::Type::BaseModel
        attr_accessor content: DedalusSDK::Models::Chat::ChatCompletionToolMessageParam::content

        attr_accessor role: :tool

        attr_accessor tool_call_id: String

        def initialize: (
          content: DedalusSDK::Models::Chat::ChatCompletionToolMessageParam::content,
          tool_call_id: String,
          ?role: :tool
        ) -> void

        def to_hash: -> {
          content: DedalusSDK::Models::Chat::ChatCompletionToolMessageParam::content,
          role: :tool,
          tool_call_id: String
        }

        type content =
          String | ::Array[DedalusSDK::Chat::ChatCompletionContentPartTextParam]

        module Content
          extend DedalusSDK::Internal::Type::Union

          def self?.variants: -> ::Array[DedalusSDK::Models::Chat::ChatCompletionToolMessageParam::content]

          ChatCompletionContentPartTextParamArray: DedalusSDK::Internal::Type::Converter
        end
      end
    end
  end
end
