module DedalusSDK
  module Models
    class ChatCompletionContentPartInputAudioParam = Chat::ChatCompletionContentPartInputAudioParam

    module Chat
      type chat_completion_content_part_input_audio_param =
        {
          input_audio: DedalusSDK::Chat::ChatCompletionContentPartInputAudioParam::InputAudio,
          type: :input_audio
        }

      class ChatCompletionContentPartInputAudioParam < DedalusSDK::Internal::Type::BaseModel
        attr_accessor input_audio: DedalusSDK::Chat::ChatCompletionContentPartInputAudioParam::InputAudio

        attr_accessor type: :input_audio

        def initialize: (
          input_audio: DedalusSDK::Chat::ChatCompletionContentPartInputAudioParam::InputAudio,
          ?type: :input_audio
        ) -> void

        def to_hash: -> {
          input_audio: DedalusSDK::Chat::ChatCompletionContentPartInputAudioParam::InputAudio,
          type: :input_audio
        }

        type input_audio =
          {
            data: String,
            format_: DedalusSDK::Models::Chat::ChatCompletionContentPartInputAudioParam::InputAudio::format_
          }

        class InputAudio < DedalusSDK::Internal::Type::BaseModel
          attr_accessor data: String

          attr_accessor format_: DedalusSDK::Models::Chat::ChatCompletionContentPartInputAudioParam::InputAudio::format_

          def initialize: (
            data: String,
            format_: DedalusSDK::Models::Chat::ChatCompletionContentPartInputAudioParam::InputAudio::format_
          ) -> void

          def to_hash: -> {
            data: String,
            format_: DedalusSDK::Models::Chat::ChatCompletionContentPartInputAudioParam::InputAudio::format_
          }

          type format_ = :wav | :mp3

          module Format
            extend DedalusSDK::Internal::Type::Enum

            WAV: :wav
            MP3: :mp3

            def self?.values: -> ::Array[DedalusSDK::Models::Chat::ChatCompletionContentPartInputAudioParam::InputAudio::format_]
          end
        end
      end
    end
  end
end
