module DedalusSDK
  module Resources
    class Audio
      class Speech
        def create: (
          input: String,
          model: DedalusSDK::Models::Audio::SpeechCreateParams::model,
          voice: DedalusSDK::Models::Audio::SpeechCreateParams::voice,
          ?instructions: String,
          ?response_format: DedalusSDK::Models::Audio::SpeechCreateParams::response_format,
          ?speed: Float,
          ?stream_format: DedalusSDK::Models::Audio::SpeechCreateParams::stream_format,
          ?request_options: DedalusSDK::request_opts
        ) -> StringIO

        def initialize: (client: DedalusSDK::Client) -> void
      end
    end
  end
end
