# frozen_string_literal: true

module DedalusSDK
  module Resources
    class Images
      # Create variations of an image.
      #
      # DALL·E 2 only. Upload an image to generate variations.
      #
      # @overload create_variation(image:, model: nil, n: nil, response_format: nil, size: nil, user: nil, request_options: {})
      #
      # @param image [Pathname, StringIO, IO, String, DedalusSDK::FilePart]
      # @param model [String, nil]
      # @param n [Integer, nil]
      # @param response_format [String, nil]
      # @param size [String, nil]
      # @param user [String, nil]
      # @param request_options [DedalusSDK::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [DedalusSDK::Models::ImagesResponse]
      #
      # @see DedalusSDK::Models::ImageCreateVariationParams
      def create_variation(params)
        parsed, options = DedalusSDK::ImageCreateVariationParams.dump_request(params)
        @client.request(
          method: :post,
          path: "v1/images/variations",
          headers: {"content-type" => "multipart/form-data"},
          body: parsed,
          model: DedalusSDK::ImagesResponse,
          options: options
        )
      end

      # Edit images using inpainting.
      #
      # Supports dall-e-2 and gpt-image-1. Upload an image and optionally a mask to
      # indicate which areas to regenerate based on the prompt.
      #
      # @overload edit(image:, prompt:, mask: nil, model: nil, n: nil, response_format: nil, size: nil, user: nil, request_options: {})
      #
      # @param image [Pathname, StringIO, IO, String, DedalusSDK::FilePart]
      # @param prompt [String]
      # @param mask [Pathname, StringIO, IO, String, DedalusSDK::FilePart, nil]
      # @param model [String, nil]
      # @param n [Integer, nil]
      # @param response_format [String, nil]
      # @param size [String, nil]
      # @param user [String, nil]
      # @param request_options [DedalusSDK::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [DedalusSDK::Models::ImagesResponse]
      #
      # @see DedalusSDK::Models::ImageEditParams
      def edit(params)
        parsed, options = DedalusSDK::ImageEditParams.dump_request(params)
        @client.request(
          method: :post,
          path: "v1/images/edits",
          headers: {"content-type" => "multipart/form-data"},
          body: parsed,
          model: DedalusSDK::ImagesResponse,
          options: options
        )
      end

      # Some parameter documentations has been truncated, see
      # {DedalusSDK::Models::ImageGenerateParams} for more details.
      #
      # Generate images from text prompts.
      #
      # Pure image generation models only (DALL-E, GPT Image). For multimodal models
      # like gemini-2.5-flash-image, use /v1/chat/completions.
      #
      # @overload generate(prompt:, background: nil, model: nil, moderation: nil, n: nil, output_compression: nil, output_format: nil, partial_images: nil, quality: nil, response_format: nil, size: nil, stream: nil, style: nil, user: nil, request_options: {})
      #
      # @param prompt [String] A text description of the desired image(s). The maximum length is 32000 characte
      #
      # @param background [Symbol, DedalusSDK::Models::CreateImageRequest::Background, nil] Allows to set transparency for the background of the generated image(s).
      #
      # @param model [String, nil] The model to use for image generation. One of `openai/dall-e-2`, `openai/dall-e-
      #
      # @param moderation [Symbol, DedalusSDK::Models::CreateImageRequest::Moderation, nil] Control the content-moderation level for images generated by `gpt-image-1`. Must
      #
      # @param n [Integer, nil] The number of images to generate. Must be between 1 and 10. For `dall-e-3`, only
      #
      # @param output_compression [Integer, nil] The compression level (0-100%) for the generated images. This parameter is only
      #
      # @param output_format [Symbol, DedalusSDK::Models::CreateImageRequest::OutputFormat, nil] The format in which the generated images are returned. This parameter is only su
      #
      # @param partial_images [Integer, nil] The number of partial images to generate. This parameter is used for
      #
      # @param quality [Symbol, DedalusSDK::Models::CreateImageRequest::Quality, nil] The quality of the image that will be generated.
      #
      # @param response_format [Symbol, DedalusSDK::Models::CreateImageRequest::ResponseFormat, nil] The format in which generated images with `dall-e-2` and `dall-e-3` are returned
      #
      # @param size [Symbol, DedalusSDK::Models::CreateImageRequest::Size, nil] The size of the generated images. Must be one of `1024x1024`, `1536x1024` (lands
      #
      # @param stream [Boolean, nil] Generate the image in streaming mode. Defaults to `false`. See the
      #
      # @param style [Symbol, DedalusSDK::Models::CreateImageRequest::Style, nil] The style of the generated images. This parameter is only supported for `dall-e-
      #
      # @param user [String, nil] A unique identifier representing your end-user, which can help OpenAI to monitor
      #
      # @param request_options [DedalusSDK::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [DedalusSDK::Models::ImagesResponse]
      #
      # @see DedalusSDK::Models::ImageGenerateParams
      def generate(params)
        parsed, options = DedalusSDK::ImageGenerateParams.dump_request(params)
        @client.request(
          method: :post,
          path: "v1/images/generations",
          body: parsed,
          model: DedalusSDK::ImagesResponse,
          options: options
        )
      end

      # @api private
      #
      # @param client [DedalusSDK::Client]
      def initialize(client:)
        @client = client
      end
    end
  end
end
