# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "dedalus_sdk/version"
require_relative "dedalus_sdk/internal/util"
require_relative "dedalus_sdk/internal/type/converter"
require_relative "dedalus_sdk/internal/type/unknown"
require_relative "dedalus_sdk/internal/type/boolean"
require_relative "dedalus_sdk/internal/type/file_input"
require_relative "dedalus_sdk/internal/type/enum"
require_relative "dedalus_sdk/internal/type/union"
require_relative "dedalus_sdk/internal/type/array_of"
require_relative "dedalus_sdk/internal/type/hash_of"
require_relative "dedalus_sdk/internal/type/base_model"
require_relative "dedalus_sdk/internal/type/base_page"
require_relative "dedalus_sdk/internal/type/base_stream"
require_relative "dedalus_sdk/internal/type/request_parameters"
require_relative "dedalus_sdk/internal"
require_relative "dedalus_sdk/request_options"
require_relative "dedalus_sdk/file_part"
require_relative "dedalus_sdk/errors"
require_relative "dedalus_sdk/internal/transport/base_client"
require_relative "dedalus_sdk/internal/transport/pooled_net_requester"
require_relative "dedalus_sdk/client"
require_relative "dedalus_sdk/internal/stream"
require_relative "dedalus_sdk/models/chat/chat_completion_create_params"
require_relative "dedalus_sdk/models/create_embedding_request"
require_relative "dedalus_sdk/models/create_image_request"
require_relative "dedalus_sdk/models/ocr_request"
require_relative "dedalus_sdk/models/audio/speech_create_params"
require_relative "dedalus_sdk/models/audio/transcription_create_params"
require_relative "dedalus_sdk/models/audio/transcription_create_response"
require_relative "dedalus_sdk/models/audio/translation_create_params"
require_relative "dedalus_sdk/models/audio/translation_create_response"
require_relative "dedalus_sdk/models/chat/audio"
require_relative "dedalus_sdk/models/chat/chat_completion"
require_relative "dedalus_sdk/models/chat/chat_completion_assistant_message_param"
require_relative "dedalus_sdk/models/chat/chat_completion_audio_param"
require_relative "dedalus_sdk/models/chat/chat_completion_chunk"
require_relative "dedalus_sdk/models/chat/chat_completion_content_part_file_param"
require_relative "dedalus_sdk/models/chat/chat_completion_content_part_image_param"
require_relative "dedalus_sdk/models/chat/chat_completion_content_part_input_audio_param"
require_relative "dedalus_sdk/models/chat/chat_completion_content_part_refusal_param"
require_relative "dedalus_sdk/models/chat/chat_completion_content_part_text_param"
require_relative "dedalus_sdk/models/chat/chat_completion_developer_message_param"
require_relative "dedalus_sdk/models/chat/chat_completion_function_message_param"
require_relative "dedalus_sdk/models/chat/chat_completion_functions"
require_relative "dedalus_sdk/models/chat/chat_completion_message"
require_relative "dedalus_sdk/models/chat/chat_completion_message_custom_tool_call"
require_relative "dedalus_sdk/models/chat/chat_completion_message_tool_call"
require_relative "dedalus_sdk/models/chat/chat_completion_system_message_param"
require_relative "dedalus_sdk/models/chat/chat_completion_token_logprob"
require_relative "dedalus_sdk/models/chat/chat_completion_tool_message_param"
require_relative "dedalus_sdk/models/chat/chat_completion_tool_param"
require_relative "dedalus_sdk/models/chat/chat_completion_user_message_param"
require_relative "dedalus_sdk/models/chat/choice"
require_relative "dedalus_sdk/models/chat/choice_delta"
require_relative "dedalus_sdk/models/chat/choice_delta_tool_call"
require_relative "dedalus_sdk/models/chat/choice_logprobs"
require_relative "dedalus_sdk/models/chat/completion_create_params"
require_relative "dedalus_sdk/models/chat/completion_tokens_details"
require_relative "dedalus_sdk/models/chat/completion_usage"
require_relative "dedalus_sdk/models/chat/deferred_call_response"
require_relative "dedalus_sdk/models/chat/input_token_details"
require_relative "dedalus_sdk/models/chat/prediction_content"
require_relative "dedalus_sdk/models/chat/prompt_tokens_details"
require_relative "dedalus_sdk/models/chat/stream_choice"
require_relative "dedalus_sdk/models/chat/stream_choice_logprobs"
require_relative "dedalus_sdk/models/chat/thinking_config_disabled"
require_relative "dedalus_sdk/models/chat/thinking_config_enabled"
require_relative "dedalus_sdk/models/chat/tool_choice_any"
require_relative "dedalus_sdk/models/chat/tool_choice_auto"
require_relative "dedalus_sdk/models/chat/tool_choice_none"
require_relative "dedalus_sdk/models/chat/tool_choice_tool"
require_relative "dedalus_sdk/models/create_embedding_response"
require_relative "dedalus_sdk/models/credential"
require_relative "dedalus_sdk/models/dedalus_model"
require_relative "dedalus_sdk/models/dedalus_model_choice"
require_relative "dedalus_sdk/models/embedding_create_params"
require_relative "dedalus_sdk/models/function_definition"
require_relative "dedalus_sdk/models/image"
require_relative "dedalus_sdk/models/image_create_variation_params"
require_relative "dedalus_sdk/models/image_edit_params"
require_relative "dedalus_sdk/models/image_generate_params"
require_relative "dedalus_sdk/models/images_response"
require_relative "dedalus_sdk/models/json_object_input"
require_relative "dedalus_sdk/models/json_value_input"
require_relative "dedalus_sdk/models/list_models_response"
require_relative "dedalus_sdk/models/mcp_credentials"
require_relative "dedalus_sdk/models/mcp_servers"
require_relative "dedalus_sdk/models/mcp_server_spec"
require_relative "dedalus_sdk/models/mcp_tool_result"
require_relative "dedalus_sdk/models/model"
require_relative "dedalus_sdk/models/model_list_params"
require_relative "dedalus_sdk/models/model_retrieve_params"
require_relative "dedalus_sdk/models/model_settings"
require_relative "dedalus_sdk/models/ocr_document"
require_relative "dedalus_sdk/models/ocr_page"
require_relative "dedalus_sdk/models/ocr_process_params"
require_relative "dedalus_sdk/models/ocr_response"
require_relative "dedalus_sdk/models/reasoning"
require_relative "dedalus_sdk/models/response"
require_relative "dedalus_sdk/models/response_create_params"
require_relative "dedalus_sdk/models/response_format_json_object"
require_relative "dedalus_sdk/models/response_format_json_schema"
require_relative "dedalus_sdk/models/response_format_text"
require_relative "dedalus_sdk/models/tool_choice"
require_relative "dedalus_sdk/models/voice_ids_or_custom_voice"
require_relative "dedalus_sdk/models"
require_relative "dedalus_sdk/resources/audio"
require_relative "dedalus_sdk/resources/audio/speech"
require_relative "dedalus_sdk/resources/audio/transcriptions"
require_relative "dedalus_sdk/resources/audio/translations"
require_relative "dedalus_sdk/resources/chat"
require_relative "dedalus_sdk/resources/chat/completions"
require_relative "dedalus_sdk/resources/embeddings"
require_relative "dedalus_sdk/resources/images"
require_relative "dedalus_sdk/resources/models"
require_relative "dedalus_sdk/resources/ocr"
require_relative "dedalus_sdk/resources/responses"
