# frozen_string_literal: true

module DedalusSDK
  module Models
    module Chat
      class ChatCompletionContentPartRefusalParam < DedalusSDK::Internal::Type::BaseModel
        # @!attribute refusal
        #   The refusal message generated by the model.
        #
        #   @return [String]
        required :refusal, String

        # @!attribute type
        #   The type of the content part.
        #
        #   @return [Symbol, :refusal]
        required :type, const: :refusal

        # @!method initialize(refusal:, type: :refusal)
        #   Schema for ChatCompletionRequestMessageContentPartRefusal.
        #
        #   Fields:
        #
        #   - type (required): Literal["refusal"]
        #   - refusal (required): str
        #
        #   @param refusal [String] The refusal message generated by the model.
        #
        #   @param type [Symbol, :refusal] The type of the content part.
      end
    end

    ChatCompletionContentPartRefusalParam = Chat::ChatCompletionContentPartRefusalParam
  end
end
