# frozen_string_literal: true

module DedalusSDK
  module Models
    module Chat
      class ChatCompletionMessageCustomToolCall < DedalusSDK::Internal::Type::BaseModel
        # @!attribute id
        #   The ID of the tool call.
        #
        #   @return [String]
        required :id, String

        # @!attribute custom
        #   The custom tool that the model called.
        #
        #   Fields:
        #
        #   - name (required): str
        #   - input (required): str
        #
        #   @return [DedalusSDK::Models::Chat::ChatCompletionMessageCustomToolCall::Custom]
        required :custom, -> { DedalusSDK::Chat::ChatCompletionMessageCustomToolCall::Custom }

        # @!attribute type
        #   The type of the tool. Always `custom`.
        #
        #   @return [Symbol, :custom]
        required :type, const: :custom

        # @!method initialize(id:, custom:, type: :custom)
        #   Some parameter documentations has been truncated, see
        #   {DedalusSDK::Models::Chat::ChatCompletionMessageCustomToolCall} for more
        #   details.
        #
        #   A call to a custom tool created by the model.
        #
        #   Fields:
        #
        #   - id (required): str
        #   - type (required): Literal["custom"]
        #   - custom (required): ChatCompletionMessageCustomToolCallCustom
        #
        #   @param id [String] The ID of the tool call.
        #
        #   @param custom [DedalusSDK::Models::Chat::ChatCompletionMessageCustomToolCall::Custom] The custom tool that the model called.
        #
        #   @param type [Symbol, :custom] The type of the tool. Always `custom`.

        # @see DedalusSDK::Models::Chat::ChatCompletionMessageCustomToolCall#custom
        class Custom < DedalusSDK::Internal::Type::BaseModel
          # @!attribute input
          #   The input for the custom tool call generated by the model.
          #
          #   @return [String]
          required :input, String

          # @!attribute name
          #   The name of the custom tool to call.
          #
          #   @return [String]
          required :name, String

          # @!method initialize(input:, name:)
          #   The custom tool that the model called.
          #
          #   Fields:
          #
          #   - name (required): str
          #   - input (required): str
          #
          #   @param input [String] The input for the custom tool call generated by the model.
          #
          #   @param name [String] The name of the custom tool to call.
        end
      end
    end

    ChatCompletionMessageCustomToolCall = Chat::ChatCompletionMessageCustomToolCall
  end
end
