# frozen_string_literal: true

module DedalusSDK
  module Models
    module Chat
      class ChatCompletionMessage < DedalusSDK::Internal::Type::BaseModel
        # @!attribute content
        #   The contents of the message.
        #
        #   @return [String, nil]
        required :content, String, nil?: true

        # @!attribute refusal
        #   The refusal message generated by the model.
        #
        #   @return [String, nil]
        required :refusal, String, nil?: true

        # @!attribute role
        #   The role of the author of this message.
        #
        #   @return [Symbol, :assistant]
        required :role, const: :assistant

        # @!attribute annotations
        #   Annotations for the message, when applicable, as when using the
        #   [web search tool](/docs/guides/tools-web-search?api-mode=chat).
        #
        #   @return [Array<DedalusSDK::Models::Chat::ChatCompletionMessage::Annotation>, nil]
        optional :annotations,
                 -> { DedalusSDK::Internal::Type::ArrayOf[DedalusSDK::Chat::ChatCompletionMessage::Annotation] }

        # @!attribute audio
        #   If the audio output modality is requested, this object contains data about the
        #   audio response from the model. [Learn more](/docs/guides/audio).
        #
        #   Fields:
        #
        #   - id (required): str
        #   - expires_at (required): int
        #   - data (required): str
        #   - transcript (required): str
        #
        #   @return [DedalusSDK::Models::Chat::ChatCompletionMessage::Audio, nil]
        optional :audio, -> { DedalusSDK::Chat::ChatCompletionMessage::Audio }, nil?: true

        # @!attribute function_call
        #   Deprecated and replaced by `tool_calls`. The name and arguments of a function
        #   that should be called, as generated by the model.
        #
        #   Fields:
        #
        #   - arguments (required): str
        #   - name (required): str
        #
        #   @return [DedalusSDK::Models::Chat::ChatCompletionMessage::FunctionCall, nil]
        optional :function_call, -> { DedalusSDK::Chat::ChatCompletionMessage::FunctionCall }

        # @!attribute tool_calls
        #   The tool calls generated by the model, such as function calls.
        #
        #   @return [Array<DedalusSDK::Models::Chat::ChatCompletionMessageToolCall, DedalusSDK::Models::Chat::ChatCompletionMessageCustomToolCall>, nil]
        optional :tool_calls,
                 -> { DedalusSDK::Internal::Type::ArrayOf[union: DedalusSDK::Chat::ChatCompletionMessage::ToolCall] }

        # @!method initialize(content:, refusal:, annotations: nil, audio: nil, function_call: nil, tool_calls: nil, role: :assistant)
        #   Some parameter documentations has been truncated, see
        #   {DedalusSDK::Models::Chat::ChatCompletionMessage} for more details.
        #
        #   A chat completion message generated by the model.
        #
        #   Fields:
        #
        #   - content (required): str | None
        #   - refusal (required): str | None
        #   - tool_calls (optional): ChatCompletionMessageToolCalls
        #   - annotations (optional): list[AnnotationsItem]
        #   - role (required): Literal["assistant"]
        #   - function_call (optional): ChatCompletionResponseMessageFunctionCall
        #   - audio (optional): ChatCompletionResponseMessageAudio | None
        #
        #   @param content [String, nil] The contents of the message.
        #
        #   @param refusal [String, nil] The refusal message generated by the model.
        #
        #   @param annotations [Array<DedalusSDK::Models::Chat::ChatCompletionMessage::Annotation>] Annotations for the message, when applicable, as when using the
        #
        #   @param audio [DedalusSDK::Models::Chat::ChatCompletionMessage::Audio, nil] If the audio output modality is requested, this object contains data
        #
        #   @param function_call [DedalusSDK::Models::Chat::ChatCompletionMessage::FunctionCall] Deprecated and replaced by `tool_calls`. The name and arguments of a function th
        #
        #   @param tool_calls [Array<DedalusSDK::Models::Chat::ChatCompletionMessageToolCall, DedalusSDK::Models::Chat::ChatCompletionMessageCustomToolCall>] The tool calls generated by the model, such as function calls.
        #
        #   @param role [Symbol, :assistant] The role of the author of this message.

        class Annotation < DedalusSDK::Internal::Type::BaseModel
          # @!attribute type
          #   The type of the URL citation. Always `url_citation`.
          #
          #   @return [Symbol, :url_citation]
          required :type, const: :url_citation

          # @!attribute url_citation
          #   A URL citation when using web search.
          #
          #   Fields:
          #
          #   - end_index (required): int
          #   - start_index (required): int
          #   - url (required): str
          #   - title (required): str
          #
          #   @return [DedalusSDK::Models::Chat::ChatCompletionMessage::Annotation::URLCitation]
          required :url_citation, -> { DedalusSDK::Chat::ChatCompletionMessage::Annotation::URLCitation }

          # @!method initialize(url_citation:, type: :url_citation)
          #   Some parameter documentations has been truncated, see
          #   {DedalusSDK::Models::Chat::ChatCompletionMessage::Annotation} for more details.
          #
          #   A URL citation when using web search.
          #
          #   Fields:
          #
          #   - type (required): Literal["url_citation"]
          #   - url_citation (required): UrlCitation
          #
          #   @param url_citation [DedalusSDK::Models::Chat::ChatCompletionMessage::Annotation::URLCitation] A URL citation when using web search.
          #
          #   @param type [Symbol, :url_citation] The type of the URL citation. Always `url_citation`.

          # @see DedalusSDK::Models::Chat::ChatCompletionMessage::Annotation#url_citation
          class URLCitation < DedalusSDK::Internal::Type::BaseModel
            # @!attribute end_index
            #   The index of the last character of the URL citation in the message.
            #
            #   @return [Integer]
            required :end_index, Integer

            # @!attribute start_index
            #   The index of the first character of the URL citation in the message.
            #
            #   @return [Integer]
            required :start_index, Integer

            # @!attribute title
            #   The title of the web resource.
            #
            #   @return [String]
            required :title, String

            # @!attribute url
            #   The URL of the web resource.
            #
            #   @return [String]
            required :url, String

            # @!method initialize(end_index:, start_index:, title:, url:)
            #   A URL citation when using web search.
            #
            #   Fields:
            #
            #   - end_index (required): int
            #   - start_index (required): int
            #   - url (required): str
            #   - title (required): str
            #
            #   @param end_index [Integer] The index of the last character of the URL citation in the message.
            #
            #   @param start_index [Integer] The index of the first character of the URL citation in the message.
            #
            #   @param title [String] The title of the web resource.
            #
            #   @param url [String] The URL of the web resource.
          end
        end

        # @see DedalusSDK::Models::Chat::ChatCompletionMessage#audio
        class Audio < DedalusSDK::Internal::Type::BaseModel
          # @!attribute id
          #   Unique identifier for this audio response.
          #
          #   @return [String]
          required :id, String

          # @!attribute data
          #   Base64 encoded audio bytes generated by the model, in the format specified in
          #   the request.
          #
          #   @return [String]
          required :data, String

          # @!attribute expires_at
          #   The Unix timestamp (in seconds) for when this audio response will no longer be
          #   accessible on the server for use in multi-turn conversations.
          #
          #   @return [Integer]
          required :expires_at, Integer

          # @!attribute transcript
          #   Transcript of the audio generated by the model.
          #
          #   @return [String]
          required :transcript, String

          # @!method initialize(id:, data:, expires_at:, transcript:)
          #   Some parameter documentations has been truncated, see
          #   {DedalusSDK::Models::Chat::ChatCompletionMessage::Audio} for more details.
          #
          #   If the audio output modality is requested, this object contains data about the
          #   audio response from the model. [Learn more](/docs/guides/audio).
          #
          #   Fields:
          #
          #   - id (required): str
          #   - expires_at (required): int
          #   - data (required): str
          #   - transcript (required): str
          #
          #   @param id [String] Unique identifier for this audio response.
          #
          #   @param data [String] Base64 encoded audio bytes generated by the model, in the format
          #
          #   @param expires_at [Integer] The Unix timestamp (in seconds) for when this audio response will
          #
          #   @param transcript [String] Transcript of the audio generated by the model.
        end

        # @see DedalusSDK::Models::Chat::ChatCompletionMessage#function_call
        class FunctionCall < DedalusSDK::Internal::Type::BaseModel
          # @!attribute arguments
          #   The arguments to call the function with, as generated by the model in JSON
          #   format. Note that the model does not always generate valid JSON, and may
          #   hallucinate parameters not defined by your function schema. Validate the
          #   arguments in your code before calling your function.
          #
          #   @return [String]
          required :arguments, String

          # @!attribute name
          #   The name of the function to call.
          #
          #   @return [String]
          required :name, String

          # @!method initialize(arguments:, name:)
          #   Some parameter documentations has been truncated, see
          #   {DedalusSDK::Models::Chat::ChatCompletionMessage::FunctionCall} for more
          #   details.
          #
          #   Deprecated and replaced by `tool_calls`. The name and arguments of a function
          #   that should be called, as generated by the model.
          #
          #   Fields:
          #
          #   - arguments (required): str
          #   - name (required): str
          #
          #   @param arguments [String] The arguments to call the function with, as generated by the model in JSON forma
          #
          #   @param name [String] The name of the function to call.
        end

        # A call to a function tool created by the model.
        #
        # Fields:
        #
        # - id (required): str
        # - type (required): Literal["function"]
        # - function (required): ChatCompletionMessageToolCallFunction
        # - thought_signature (optional): str
        module ToolCall
          extend DedalusSDK::Internal::Type::Union

          discriminator :type

          # A call to a function tool created by the model.
          #
          # Fields:
          # - id (required): str
          # - type (required): Literal["function"]
          # - function (required): ChatCompletionMessageToolCallFunction
          # - thought_signature (optional): str
          variant :function, -> { DedalusSDK::Chat::ChatCompletionMessageToolCall }

          # A call to a custom tool created by the model.
          #
          # Fields:
          # - id (required): str
          # - type (required): Literal["custom"]
          # - custom (required): ChatCompletionMessageCustomToolCallCustom
          variant :custom, -> { DedalusSDK::Chat::ChatCompletionMessageCustomToolCall }

          # @!method self.variants
          #   @return [Array(DedalusSDK::Models::Chat::ChatCompletionMessageToolCall, DedalusSDK::Models::Chat::ChatCompletionMessageCustomToolCall)]
        end
      end
    end

    ChatCompletionMessage = Chat::ChatCompletionMessage
  end
end
