# frozen_string_literal: true

module DedalusSDK
  module Models
    module Chat
      class ChatCompletionAssistantMessageParam < DedalusSDK::Internal::Type::BaseModel
        # @!attribute role
        #   The role of the messages author, in this case `assistant`.
        #
        #   @return [Symbol, :assistant]
        required :role, const: :assistant

        # @!attribute audio
        #   Data about a previous audio response from the model.
        #   [Learn more](/docs/guides/audio).
        #
        #   Fields:
        #
        #   - id (required): str
        #
        #   @return [DedalusSDK::Models::Chat::Audio, nil]
        optional :audio, -> { DedalusSDK::Chat::Audio }, nil?: true

        # @!attribute content
        #   The contents of the assistant message. Required unless `tool_calls` or
        #   `function_call` is specified.
        #
        #   @return [String, Array<DedalusSDK::Models::Chat::ChatCompletionContentPartTextParam, DedalusSDK::Models::Chat::ChatCompletionContentPartRefusalParam>, nil]
        optional :content,
                 union: -> { DedalusSDK::Chat::ChatCompletionAssistantMessageParam::Content },
                 nil?: true

        # @!attribute function_call
        #   Deprecated and replaced by `tool_calls`. The name and arguments of a function
        #   that should be called, as generated by the model.
        #
        #   Fields:
        #
        #   - arguments (required): str
        #   - name (required): str
        #
        #   @return [DedalusSDK::Models::Chat::ChatCompletionAssistantMessageParam::FunctionCall, nil]
        optional :function_call,
                 -> { DedalusSDK::Chat::ChatCompletionAssistantMessageParam::FunctionCall },
                 nil?: true

        # @!attribute name
        #   An optional name for the participant. Provides the model information to
        #   differentiate between participants of the same role.
        #
        #   @return [String, nil]
        optional :name, String

        # @!attribute refusal
        #   The refusal message by the assistant.
        #
        #   @return [String, nil]
        optional :refusal, String, nil?: true

        # @!attribute tool_calls
        #   The tool calls generated by the model, such as function calls.
        #
        #   @return [Array<DedalusSDK::Models::Chat::ChatCompletionMessageToolCall, DedalusSDK::Models::Chat::ChatCompletionMessageCustomToolCall>, nil]
        optional :tool_calls,
                 -> { DedalusSDK::Internal::Type::ArrayOf[union: DedalusSDK::Chat::ChatCompletionAssistantMessageParam::ToolCall] }

        # @!method initialize(audio: nil, content: nil, function_call: nil, name: nil, refusal: nil, tool_calls: nil, role: :assistant)
        #   Some parameter documentations has been truncated, see
        #   {DedalusSDK::Models::Chat::ChatCompletionAssistantMessageParam} for more
        #   details.
        #
        #   Messages sent by the model in response to user messages.
        #
        #   Fields:
        #
        #   - content (optional): str |
        #     Annotated[list[ChatCompletionRequestAssistantMessageContentPart], MinLen(1),
        #     ArrayTitle("ChatCompletionRequestAssistantMessageContentArray")] | None
        #   - refusal (optional): str | None
        #   - role (required): Literal["assistant"]
        #   - name (optional): str
        #   - audio (optional): Audio | None
        #   - tool_calls (optional): ChatCompletionMessageToolCalls
        #   - function_call (optional): FunctionCall | None
        #
        #   @param audio [DedalusSDK::Models::Chat::Audio, nil] Data about a previous audio response from the model.
        #
        #   @param content [String, Array<DedalusSDK::Models::Chat::ChatCompletionContentPartTextParam, DedalusSDK::Models::Chat::ChatCompletionContentPartRefusalParam>, nil] The contents of the assistant message. Required unless `tool_calls` or `function
        #
        #   @param function_call [DedalusSDK::Models::Chat::ChatCompletionAssistantMessageParam::FunctionCall, nil] Deprecated and replaced by `tool_calls`. The name and arguments of a function th
        #
        #   @param name [String] An optional name for the participant. Provides the model information to differen
        #
        #   @param refusal [String, nil] The refusal message by the assistant.
        #
        #   @param tool_calls [Array<DedalusSDK::Models::Chat::ChatCompletionMessageToolCall, DedalusSDK::Models::Chat::ChatCompletionMessageCustomToolCall>] The tool calls generated by the model, such as function calls.
        #
        #   @param role [Symbol, :assistant] The role of the messages author, in this case `assistant`.

        # The contents of the assistant message. Required unless `tool_calls` or
        # `function_call` is specified.
        #
        # @see DedalusSDK::Models::Chat::ChatCompletionAssistantMessageParam#content
        module Content
          extend DedalusSDK::Internal::Type::Union

          variant String

          variant -> { DedalusSDK::Models::Chat::ChatCompletionAssistantMessageParam::Content::ChatCompletionRequestAssistantMessageContent2DArray }

          # Learn about [text inputs](/docs/guides/text-generation).
          #
          # Fields:
          #
          # - type (required): Literal["text"]
          # - text (required): str
          module ChatCompletionRequestAssistantMessageContentArray
            extend DedalusSDK::Internal::Type::Union

            discriminator :type

            # Learn about [text inputs](/docs/guides/text-generation).
            #
            # Fields:
            # - type (required): Literal["text"]
            # - text (required): str
            variant :text, -> { DedalusSDK::Chat::ChatCompletionContentPartTextParam }

            # Schema for ChatCompletionRequestMessageContentPartRefusal.
            #
            # Fields:
            # - type (required): Literal["refusal"]
            # - refusal (required): str
            variant :refusal, -> { DedalusSDK::Chat::ChatCompletionContentPartRefusalParam }

            # @!method self.variants
            #   @return [Array(DedalusSDK::Models::Chat::ChatCompletionContentPartTextParam, DedalusSDK::Models::Chat::ChatCompletionContentPartRefusalParam)]
          end

          # @!method self.variants
          #   @return [Array(String, Array<DedalusSDK::Models::Chat::ChatCompletionContentPartTextParam, DedalusSDK::Models::Chat::ChatCompletionContentPartRefusalParam>)]

          # @type [DedalusSDK::Internal::Type::Converter]
          ChatCompletionRequestAssistantMessageContent2DArray =
            DedalusSDK::Internal::Type::ArrayOf[
              union: -> { DedalusSDK::Chat::ChatCompletionAssistantMessageParam::Content::ChatCompletionRequestAssistantMessageContentArray }
            ]
        end

        # @see DedalusSDK::Models::Chat::ChatCompletionAssistantMessageParam#function_call
        class FunctionCall < DedalusSDK::Internal::Type::BaseModel
          # @!attribute arguments
          #   The arguments to call the function with, as generated by the model in JSON
          #   format. Note that the model does not always generate valid JSON, and may
          #   hallucinate parameters not defined by your function schema. Validate the
          #   arguments in your code before calling your function.
          #
          #   @return [String]
          required :arguments, String

          # @!attribute name
          #   The name of the function to call.
          #
          #   @return [String]
          required :name, String

          # @!method initialize(arguments:, name:)
          #   Some parameter documentations has been truncated, see
          #   {DedalusSDK::Models::Chat::ChatCompletionAssistantMessageParam::FunctionCall}
          #   for more details.
          #
          #   Deprecated and replaced by `tool_calls`. The name and arguments of a function
          #   that should be called, as generated by the model.
          #
          #   Fields:
          #
          #   - arguments (required): str
          #   - name (required): str
          #
          #   @param arguments [String] The arguments to call the function with, as generated by the model in JSON forma
          #
          #   @param name [String] The name of the function to call.
        end

        # A call to a function tool created by the model.
        #
        # Fields:
        #
        # - id (required): str
        # - type (required): Literal["function"]
        # - function (required): ChatCompletionMessageToolCallFunction
        # - thought_signature (optional): str
        module ToolCall
          extend DedalusSDK::Internal::Type::Union

          discriminator :type

          # A call to a function tool created by the model.
          #
          # Fields:
          # - id (required): str
          # - type (required): Literal["function"]
          # - function (required): ChatCompletionMessageToolCallFunction
          # - thought_signature (optional): str
          variant :function, -> { DedalusSDK::Chat::ChatCompletionMessageToolCall }

          # A call to a custom tool created by the model.
          #
          # Fields:
          # - id (required): str
          # - type (required): Literal["custom"]
          # - custom (required): ChatCompletionMessageCustomToolCallCustom
          variant :custom, -> { DedalusSDK::Chat::ChatCompletionMessageCustomToolCall }

          # @!method self.variants
          #   @return [Array(DedalusSDK::Models::Chat::ChatCompletionMessageToolCall, DedalusSDK::Models::Chat::ChatCompletionMessageCustomToolCall)]
        end
      end
    end

    ChatCompletionAssistantMessageParam = Chat::ChatCompletionAssistantMessageParam
  end
end
