# frozen_string_literal: true

module DedalusSDK
  module Models
    module Chat
      class ChatCompletionMessageToolCall < DedalusSDK::Internal::Type::BaseModel
        # @!attribute id
        #   The ID of the tool call.
        #
        #   @return [String]
        required :id, String

        # @!attribute function
        #   The function that the model called.
        #
        #   Fields:
        #
        #   - name (required): str
        #   - arguments (required): str
        #
        #   @return [DedalusSDK::Models::Chat::ChatCompletionMessageToolCall::Function]
        required :function, -> { DedalusSDK::Chat::ChatCompletionMessageToolCall::Function }

        # @!attribute type
        #   The type of the tool. Currently, only `function` is supported.
        #
        #   @return [Symbol, :function]
        required :type, const: :function

        # @!attribute thought_signature
        #   Opaque signature for thought continuity in multi-turn tool use (Google-specific,
        #   base64 encoded)
        #
        #   @return [String, nil]
        optional :thought_signature, String, nil?: true

        # @!method initialize(id:, function:, thought_signature: nil, type: :function)
        #   Some parameter documentations has been truncated, see
        #   {DedalusSDK::Models::Chat::ChatCompletionMessageToolCall} for more details.
        #
        #   A call to a function tool created by the model.
        #
        #   Fields:
        #
        #   - id (required): str
        #   - type (required): Literal["function"]
        #   - function (required): ChatCompletionMessageToolCallFunction
        #   - thought_signature (optional): str
        #
        #   @param id [String] The ID of the tool call.
        #
        #   @param function [DedalusSDK::Models::Chat::ChatCompletionMessageToolCall::Function] The function that the model called.
        #
        #   @param thought_signature [String, nil] Opaque signature for thought continuity in multi-turn tool use (Google-specific,
        #
        #   @param type [Symbol, :function] The type of the tool. Currently, only `function` is supported.

        # @see DedalusSDK::Models::Chat::ChatCompletionMessageToolCall#function
        class Function < DedalusSDK::Internal::Type::BaseModel
          # @!attribute arguments
          #   The arguments to call the function with, as generated by the model in JSON
          #   format. Note that the model does not always generate valid JSON, and may
          #   hallucinate parameters not defined by your function schema. Validate the
          #   arguments in your code before calling your function.
          #
          #   @return [String]
          required :arguments, String

          # @!attribute name
          #   The name of the function to call.
          #
          #   @return [String]
          required :name, String

          # @!method initialize(arguments:, name:)
          #   Some parameter documentations has been truncated, see
          #   {DedalusSDK::Models::Chat::ChatCompletionMessageToolCall::Function} for more
          #   details.
          #
          #   The function that the model called.
          #
          #   Fields:
          #
          #   - name (required): str
          #   - arguments (required): str
          #
          #   @param arguments [String] The arguments to call the function with, as generated by the model in JSON forma
          #
          #   @param name [String] The name of the function to call.
        end
      end
    end

    ChatCompletionMessageToolCall = Chat::ChatCompletionMessageToolCall
  end
end
