# frozen_string_literal: true

module DedalusSDK
  module Models
    module Chat
      class ChoiceDelta < DedalusSDK::Internal::Type::BaseModel
        # @!attribute content
        #   The contents of the chunk message.
        #
        #   @return [String, nil]
        optional :content, String, nil?: true

        # @!attribute function_call
        #   Deprecated and replaced by `tool_calls`. The name and arguments of a function
        #   that should be called, as generated by the model.
        #
        #   Fields:
        #
        #   - arguments (optional): str
        #   - name (optional): str
        #
        #   @return [DedalusSDK::Models::Chat::ChoiceDelta::FunctionCall, nil]
        optional :function_call, -> { DedalusSDK::Chat::ChoiceDelta::FunctionCall }

        # @!attribute refusal
        #   The refusal message generated by the model.
        #
        #   @return [String, nil]
        optional :refusal, String, nil?: true

        # @!attribute role
        #   The role of the author of this message.
        #
        #   @return [Symbol, DedalusSDK::Models::Chat::ChoiceDelta::Role, nil]
        optional :role, enum: -> { DedalusSDK::Chat::ChoiceDelta::Role }

        # @!attribute tool_calls
        #
        #   @return [Array<DedalusSDK::Models::Chat::ChoiceDeltaToolCall>, nil]
        optional :tool_calls, -> { DedalusSDK::Internal::Type::ArrayOf[DedalusSDK::Chat::ChoiceDeltaToolCall] }

        # @!method initialize(content: nil, function_call: nil, refusal: nil, role: nil, tool_calls: nil)
        #   Some parameter documentations has been truncated, see
        #   {DedalusSDK::Models::Chat::ChoiceDelta} for more details.
        #
        #   A chat completion delta generated by streamed model responses.
        #
        #   Fields:
        #
        #   - content (optional): str | None
        #   - function_call (optional): ChatCompletionStreamResponseDeltaFunctionCall
        #   - tool_calls (optional): list[ChatCompletionMessageToolCallChunk]
        #   - role (optional): Literal["developer", "system", "user", "assistant", "tool"]
        #   - refusal (optional): str | None
        #
        #   @param content [String, nil] The contents of the chunk message.
        #
        #   @param function_call [DedalusSDK::Models::Chat::ChoiceDelta::FunctionCall] Deprecated and replaced by `tool_calls`. The name and arguments of a function th
        #
        #   @param refusal [String, nil] The refusal message generated by the model.
        #
        #   @param role [Symbol, DedalusSDK::Models::Chat::ChoiceDelta::Role] The role of the author of this message.
        #
        #   @param tool_calls [Array<DedalusSDK::Models::Chat::ChoiceDeltaToolCall>]

        # @see DedalusSDK::Models::Chat::ChoiceDelta#function_call
        class FunctionCall < DedalusSDK::Internal::Type::BaseModel
          # @!attribute arguments
          #   The arguments to call the function with, as generated by the model in JSON
          #   format. Note that the model does not always generate valid JSON, and may
          #   hallucinate parameters not defined by your function schema. Validate the
          #   arguments in your code before calling your function.
          #
          #   @return [String, nil]
          optional :arguments, String

          # @!attribute name
          #   The name of the function to call.
          #
          #   @return [String, nil]
          optional :name, String

          # @!method initialize(arguments: nil, name: nil)
          #   Some parameter documentations has been truncated, see
          #   {DedalusSDK::Models::Chat::ChoiceDelta::FunctionCall} for more details.
          #
          #   Deprecated and replaced by `tool_calls`. The name and arguments of a function
          #   that should be called, as generated by the model.
          #
          #   Fields:
          #
          #   - arguments (optional): str
          #   - name (optional): str
          #
          #   @param arguments [String] The arguments to call the function with, as generated by the model in JSON forma
          #
          #   @param name [String] The name of the function to call.
        end

        # The role of the author of this message.
        #
        # @see DedalusSDK::Models::Chat::ChoiceDelta#role
        module Role
          extend DedalusSDK::Internal::Type::Enum

          DEVELOPER = :developer
          SYSTEM = :system
          USER = :user
          ASSISTANT = :assistant
          TOOL = :tool

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
