# frozen_string_literal: true

module DedalusSDK
  module Models
    module Chat
      class ChoiceDeltaToolCall < DedalusSDK::Internal::Type::BaseModel
        # @!attribute index
        #
        #   @return [Integer]
        required :index, Integer

        # @!attribute id
        #   The ID of the tool call.
        #
        #   @return [String, nil]
        optional :id, String

        # @!attribute function
        #   Schema for ChatCompletionMessageToolCallChunkFunction.
        #
        #   Fields:
        #
        #   - name (optional): str
        #   - arguments (optional): str
        #
        #   @return [DedalusSDK::Models::Chat::ChoiceDeltaToolCall::Function, nil]
        optional :function, -> { DedalusSDK::Chat::ChoiceDeltaToolCall::Function }

        # @!attribute type
        #   The type of the tool. Currently, only `function` is supported.
        #
        #   @return [Symbol, DedalusSDK::Models::Chat::ChoiceDeltaToolCall::Type, nil]
        optional :type, enum: -> { DedalusSDK::Chat::ChoiceDeltaToolCall::Type }

        # @!method initialize(index:, id: nil, function: nil, type: nil)
        #   Some parameter documentations has been truncated, see
        #   {DedalusSDK::Models::Chat::ChoiceDeltaToolCall} for more details.
        #
        #   Schema for ChatCompletionMessageToolCallChunk.
        #
        #   Fields:
        #
        #   - index (required): int
        #   - id (optional): str
        #   - type (optional): Literal["function"]
        #   - function (optional): ChatCompletionMessageToolCallChunkFunction
        #
        #   @param index [Integer]
        #
        #   @param id [String] The ID of the tool call.
        #
        #   @param function [DedalusSDK::Models::Chat::ChoiceDeltaToolCall::Function] Schema for ChatCompletionMessageToolCallChunkFunction.
        #
        #   @param type [Symbol, DedalusSDK::Models::Chat::ChoiceDeltaToolCall::Type] The type of the tool. Currently, only `function` is supported.

        # @see DedalusSDK::Models::Chat::ChoiceDeltaToolCall#function
        class Function < DedalusSDK::Internal::Type::BaseModel
          # @!attribute arguments
          #   The arguments to call the function with, as generated by the model in JSON
          #   format. Note that the model does not always generate valid JSON, and may
          #   hallucinate parameters not defined by your function schema. Validate the
          #   arguments in your code before calling your function.
          #
          #   @return [String, nil]
          optional :arguments, String

          # @!attribute name
          #   The name of the function to call.
          #
          #   @return [String, nil]
          optional :name, String

          # @!method initialize(arguments: nil, name: nil)
          #   Some parameter documentations has been truncated, see
          #   {DedalusSDK::Models::Chat::ChoiceDeltaToolCall::Function} for more details.
          #
          #   Schema for ChatCompletionMessageToolCallChunkFunction.
          #
          #   Fields:
          #
          #   - name (optional): str
          #   - arguments (optional): str
          #
          #   @param arguments [String] The arguments to call the function with, as generated by the model in JSON forma
          #
          #   @param name [String] The name of the function to call.
        end

        # The type of the tool. Currently, only `function` is supported.
        #
        # @see DedalusSDK::Models::Chat::ChoiceDeltaToolCall#type
        module Type
          extend DedalusSDK::Internal::Type::Enum

          FUNCTION = :function

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
