# frozen_string_literal: true

module DedalusSDK
  module Models
    module Chat
      class Choice < DedalusSDK::Internal::Type::BaseModel
        # @!attribute index
        #   The index of the choice in the list of choices.
        #
        #   @return [Integer]
        required :index, Integer

        # @!attribute message
        #   A chat completion message generated by the model.
        #
        #   @return [DedalusSDK::Models::Chat::ChatCompletionMessage]
        required :message, -> { DedalusSDK::Chat::ChatCompletionMessage }

        # @!attribute finish_reason
        #   The reason the model stopped generating tokens. This will be `stop` if the model
        #   hit a natural stop point or a provided stop sequence, `length` if the maximum
        #   number of tokens specified in the request was reached, `content_filter` if
        #   content was omitted due to a flag from our content filters, `tool_calls` if the
        #   model called a tool, or `function_call` (deprecated) if the model called a
        #   function.
        #
        #   @return [Symbol, DedalusSDK::Models::Chat::Choice::FinishReason, nil]
        optional :finish_reason, enum: -> { DedalusSDK::Chat::Choice::FinishReason }, nil?: true

        # @!attribute logprobs
        #   Log probability information for the choice.
        #
        #   @return [DedalusSDK::Models::Chat::ChoiceLogprobs, nil]
        optional :logprobs, -> { DedalusSDK::Chat::ChoiceLogprobs }, nil?: true

        # @!method initialize(index:, message:, finish_reason: nil, logprobs: nil)
        #   Some parameter documentations has been truncated, see
        #   {DedalusSDK::Models::Chat::Choice} for more details.
        #
        #   A chat completion choice.
        #
        #   OpenAI-compatible choice object for non-streaming responses. Part of the
        #   ChatCompletion response.
        #
        #   @param index [Integer] The index of the choice in the list of choices.
        #
        #   @param message [DedalusSDK::Models::Chat::ChatCompletionMessage] A chat completion message generated by the model.
        #
        #   @param finish_reason [Symbol, DedalusSDK::Models::Chat::Choice::FinishReason, nil] The reason the model stopped generating tokens. This will be `stop` if the model
        #
        #   @param logprobs [DedalusSDK::Models::Chat::ChoiceLogprobs, nil] Log probability information for the choice.

        # The reason the model stopped generating tokens. This will be `stop` if the model
        # hit a natural stop point or a provided stop sequence, `length` if the maximum
        # number of tokens specified in the request was reached, `content_filter` if
        # content was omitted due to a flag from our content filters, `tool_calls` if the
        # model called a tool, or `function_call` (deprecated) if the model called a
        # function.
        #
        # @see DedalusSDK::Models::Chat::Choice#finish_reason
        module FinishReason
          extend DedalusSDK::Internal::Type::Enum

          STOP = :stop
          LENGTH = :length
          TOOL_CALLS = :tool_calls
          CONTENT_FILTER = :content_filter
          FUNCTION_CALL = :function_call

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
