# frozen_string_literal: true

module DedalusSDK
  module Models
    module Chat
      class CompletionTokensDetails < DedalusSDK::Internal::Type::BaseModel
        # @!attribute accepted_prediction_tokens
        #   When using Predicted Outputs, the number of tokens in the prediction that
        #   appeared in the completion.
        #
        #   @return [Integer, nil]
        optional :accepted_prediction_tokens, Integer

        # @!attribute audio_tokens
        #   Audio input tokens generated by the model.
        #
        #   @return [Integer, nil]
        optional :audio_tokens, Integer

        # @!attribute reasoning_tokens
        #   Tokens generated by the model for reasoning.
        #
        #   @return [Integer, nil]
        optional :reasoning_tokens, Integer

        # @!attribute rejected_prediction_tokens
        #   When using Predicted Outputs, the number of tokens in the prediction that did
        #   not appear in the completion. However, like reasoning tokens, these tokens are
        #   still counted in the total completion tokens for purposes of billing, output,
        #   and context window limits.
        #
        #   @return [Integer, nil]
        optional :rejected_prediction_tokens, Integer

        # @!method initialize(accepted_prediction_tokens: nil, audio_tokens: nil, reasoning_tokens: nil, rejected_prediction_tokens: nil)
        #   Some parameter documentations has been truncated, see
        #   {DedalusSDK::Models::Chat::CompletionTokensDetails} for more details.
        #
        #   Breakdown of tokens used in a completion.
        #
        #   Fields:
        #
        #   - accepted_prediction_tokens (optional): int
        #   - audio_tokens (optional): int
        #   - reasoning_tokens (optional): int
        #   - rejected_prediction_tokens (optional): int
        #
        #   @param accepted_prediction_tokens [Integer] When using Predicted Outputs, the number of tokens in the
        #
        #   @param audio_tokens [Integer] Audio input tokens generated by the model.
        #
        #   @param reasoning_tokens [Integer] Tokens generated by the model for reasoning.
        #
        #   @param rejected_prediction_tokens [Integer] When using Predicted Outputs, the number of tokens in the
      end
    end
  end
end
