# frozen_string_literal: true

module DedalusSDK
  module Models
    module Chat
      class StreamChoice < DedalusSDK::Internal::Type::BaseModel
        # @!attribute delta
        #   A chat completion delta generated by streamed model responses.
        #
        #   @return [DedalusSDK::Models::Chat::ChoiceDelta]
        required :delta, -> { DedalusSDK::Chat::ChoiceDelta }

        # @!attribute finish_reason
        #   The reason the model stopped generating tokens. This will be `stop` if the model
        #   hit a natural stop point or a provided stop sequence, `length` if the maximum
        #   number of tokens specified in the request was reached, `content_filter` if
        #   content was omitted due to a flag from our content filters, `tool_calls` if the
        #   model called a tool, or `function_call` (deprecated) if the model called a
        #   function.
        #
        #   @return [Symbol, DedalusSDK::Models::Chat::StreamChoice::FinishReason, nil]
        required :finish_reason, enum: -> { DedalusSDK::Chat::StreamChoice::FinishReason }, nil?: true

        # @!attribute index
        #   The index of the choice in the list of choices.
        #
        #   @return [Integer]
        required :index, Integer

        # @!attribute logprobs
        #   Log probability information for the choice.
        #
        #   Fields:
        #
        #   - content (required): list[ChatCompletionTokenLogprob]
        #   - refusal (required): list[ChatCompletionTokenLogprob]
        #
        #   @return [DedalusSDK::Models::Chat::StreamChoiceLogprobs, nil]
        optional :logprobs, -> { DedalusSDK::Chat::StreamChoiceLogprobs }, nil?: true

        # @!method initialize(delta:, finish_reason:, index:, logprobs: nil)
        #   Some parameter documentations has been truncated, see
        #   {DedalusSDK::Models::Chat::StreamChoice} for more details.
        #
        #   Schema for ChatCompletionStreamResponseChoicesItem.
        #
        #   Fields:
        #
        #   - delta (required): ChatCompletionStreamResponseDelta
        #   - logprobs (optional): ChatCompletionStreamResponseChoicesItemLogprobs
        #   - finish_reason (required): Literal["stop", "length", "tool_calls",
        #     "content_filter", "function_call"]
        #   - index (required): int
        #
        #   @param delta [DedalusSDK::Models::Chat::ChoiceDelta] A chat completion delta generated by streamed model responses.
        #
        #   @param finish_reason [Symbol, DedalusSDK::Models::Chat::StreamChoice::FinishReason, nil] The reason the model stopped generating tokens. This will be `stop` if the model
        #
        #   @param index [Integer] The index of the choice in the list of choices.
        #
        #   @param logprobs [DedalusSDK::Models::Chat::StreamChoiceLogprobs, nil] Log probability information for the choice.

        # The reason the model stopped generating tokens. This will be `stop` if the model
        # hit a natural stop point or a provided stop sequence, `length` if the maximum
        # number of tokens specified in the request was reached, `content_filter` if
        # content was omitted due to a flag from our content filters, `tool_calls` if the
        # model called a tool, or `function_call` (deprecated) if the model called a
        # function.
        #
        # @see DedalusSDK::Models::Chat::StreamChoice#finish_reason
        module FinishReason
          extend DedalusSDK::Internal::Type::Enum

          STOP = :stop
          LENGTH = :length
          TOOL_CALLS = :tool_calls
          CONTENT_FILTER = :content_filter
          FUNCTION_CALL = :function_call

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
