# typed: strong

module DedalusSDK
  module Models
    ChatCompletionAssistantMessageParam =
      Chat::ChatCompletionAssistantMessageParam

    module Chat
      class ChatCompletionAssistantMessageParam < DedalusSDK::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              DedalusSDK::Chat::ChatCompletionAssistantMessageParam,
              DedalusSDK::Internal::AnyHash
            )
          end

        # The role of the messages author, in this case `assistant`.
        sig { returns(Symbol) }
        attr_accessor :role

        # Data about a previous audio response from the model.
        # [Learn more](/docs/guides/audio).
        #
        # Fields:
        #
        # - id (required): str
        sig { returns(T.nilable(DedalusSDK::Chat::Audio)) }
        attr_reader :audio

        sig { params(audio: T.nilable(DedalusSDK::Chat::Audio::OrHash)).void }
        attr_writer :audio

        # The contents of the assistant message. Required unless `tool_calls` or
        # `function_call` is specified.
        sig do
          returns(
            T.nilable(
              DedalusSDK::Chat::ChatCompletionAssistantMessageParam::Content::Variants
            )
          )
        end
        attr_accessor :content

        # Deprecated and replaced by `tool_calls`. The name and arguments of a function
        # that should be called, as generated by the model.
        #
        # Fields:
        #
        # - arguments (required): str
        # - name (required): str
        sig do
          returns(
            T.nilable(
              DedalusSDK::Chat::ChatCompletionAssistantMessageParam::FunctionCall
            )
          )
        end
        attr_reader :function_call

        sig do
          params(
            function_call:
              T.nilable(
                DedalusSDK::Chat::ChatCompletionAssistantMessageParam::FunctionCall::OrHash
              )
          ).void
        end
        attr_writer :function_call

        # An optional name for the participant. Provides the model information to
        # differentiate between participants of the same role.
        sig { returns(T.nilable(String)) }
        attr_reader :name

        sig { params(name: String).void }
        attr_writer :name

        # The refusal message by the assistant.
        sig { returns(T.nilable(String)) }
        attr_accessor :refusal

        # The tool calls generated by the model, such as function calls.
        sig do
          returns(
            T.nilable(
              T::Array[
                T.any(
                  DedalusSDK::Chat::ChatCompletionMessageToolCall,
                  DedalusSDK::Chat::ChatCompletionMessageCustomToolCall
                )
              ]
            )
          )
        end
        attr_reader :tool_calls

        sig do
          params(
            tool_calls:
              T::Array[
                T.any(
                  DedalusSDK::Chat::ChatCompletionMessageToolCall::OrHash,
                  DedalusSDK::Chat::ChatCompletionMessageCustomToolCall::OrHash
                )
              ]
          ).void
        end
        attr_writer :tool_calls

        # Messages sent by the model in response to user messages.
        #
        # Fields:
        #
        # - content (optional): str |
        #   Annotated[list[ChatCompletionRequestAssistantMessageContentPart], MinLen(1),
        #   ArrayTitle("ChatCompletionRequestAssistantMessageContentArray")] | None
        # - refusal (optional): str | None
        # - role (required): Literal["assistant"]
        # - name (optional): str
        # - audio (optional): Audio | None
        # - tool_calls (optional): ChatCompletionMessageToolCalls
        # - function_call (optional): FunctionCall | None
        sig do
          params(
            audio: T.nilable(DedalusSDK::Chat::Audio::OrHash),
            content:
              T.nilable(
                DedalusSDK::Chat::ChatCompletionAssistantMessageParam::Content::Variants
              ),
            function_call:
              T.nilable(
                DedalusSDK::Chat::ChatCompletionAssistantMessageParam::FunctionCall::OrHash
              ),
            name: String,
            refusal: T.nilable(String),
            tool_calls:
              T::Array[
                T.any(
                  DedalusSDK::Chat::ChatCompletionMessageToolCall::OrHash,
                  DedalusSDK::Chat::ChatCompletionMessageCustomToolCall::OrHash
                )
              ],
            role: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # Data about a previous audio response from the model.
          # [Learn more](/docs/guides/audio).
          #
          # Fields:
          #
          # - id (required): str
          audio: nil,
          # The contents of the assistant message. Required unless `tool_calls` or
          # `function_call` is specified.
          content: nil,
          # Deprecated and replaced by `tool_calls`. The name and arguments of a function
          # that should be called, as generated by the model.
          #
          # Fields:
          #
          # - arguments (required): str
          # - name (required): str
          function_call: nil,
          # An optional name for the participant. Provides the model information to
          # differentiate between participants of the same role.
          name: nil,
          # The refusal message by the assistant.
          refusal: nil,
          # The tool calls generated by the model, such as function calls.
          tool_calls: nil,
          # The role of the messages author, in this case `assistant`.
          role: :assistant
        )
        end

        sig do
          override.returns(
            {
              role: Symbol,
              audio: T.nilable(DedalusSDK::Chat::Audio),
              content:
                T.nilable(
                  DedalusSDK::Chat::ChatCompletionAssistantMessageParam::Content::Variants
                ),
              function_call:
                T.nilable(
                  DedalusSDK::Chat::ChatCompletionAssistantMessageParam::FunctionCall
                ),
              name: String,
              refusal: T.nilable(String),
              tool_calls:
                T::Array[
                  T.any(
                    DedalusSDK::Chat::ChatCompletionMessageToolCall,
                    DedalusSDK::Chat::ChatCompletionMessageCustomToolCall
                  )
                ]
            }
          )
        end
        def to_hash
        end

        # The contents of the assistant message. Required unless `tool_calls` or
        # `function_call` is specified.
        module Content
          extend DedalusSDK::Internal::Type::Union

          Variants =
            T.type_alias do
              T.any(
                String,
                T::Array[
                  DedalusSDK::Chat::ChatCompletionAssistantMessageParam::Content::ChatCompletionRequestAssistantMessageContentArray::Variants
                ]
              )
            end

          # Learn about [text inputs](/docs/guides/text-generation).
          #
          # Fields:
          #
          # - type (required): Literal["text"]
          # - text (required): str
          module ChatCompletionRequestAssistantMessageContentArray
            extend DedalusSDK::Internal::Type::Union

            Variants =
              T.type_alias do
                T.any(
                  DedalusSDK::Chat::ChatCompletionContentPartTextParam,
                  DedalusSDK::Chat::ChatCompletionContentPartRefusalParam
                )
              end

            sig do
              override.returns(
                T::Array[
                  DedalusSDK::Chat::ChatCompletionAssistantMessageParam::Content::ChatCompletionRequestAssistantMessageContentArray::Variants
                ]
              )
            end
            def self.variants
            end
          end

          sig do
            override.returns(
              T::Array[
                DedalusSDK::Chat::ChatCompletionAssistantMessageParam::Content::Variants
              ]
            )
          end
          def self.variants
          end

          ChatCompletionRequestAssistantMessageContent2DArray =
            T.let(
              DedalusSDK::Internal::Type::ArrayOf[
                union:
                  DedalusSDK::Chat::ChatCompletionAssistantMessageParam::Content::ChatCompletionRequestAssistantMessageContentArray
              ],
              DedalusSDK::Internal::Type::Converter
            )
        end

        class FunctionCall < DedalusSDK::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                DedalusSDK::Chat::ChatCompletionAssistantMessageParam::FunctionCall,
                DedalusSDK::Internal::AnyHash
              )
            end

          # The arguments to call the function with, as generated by the model in JSON
          # format. Note that the model does not always generate valid JSON, and may
          # hallucinate parameters not defined by your function schema. Validate the
          # arguments in your code before calling your function.
          sig { returns(String) }
          attr_accessor :arguments

          # The name of the function to call.
          sig { returns(String) }
          attr_accessor :name

          # Deprecated and replaced by `tool_calls`. The name and arguments of a function
          # that should be called, as generated by the model.
          #
          # Fields:
          #
          # - arguments (required): str
          # - name (required): str
          sig do
            params(arguments: String, name: String).returns(T.attached_class)
          end
          def self.new(
            # The arguments to call the function with, as generated by the model in JSON
            # format. Note that the model does not always generate valid JSON, and may
            # hallucinate parameters not defined by your function schema. Validate the
            # arguments in your code before calling your function.
            arguments:,
            # The name of the function to call.
            name:
          )
          end

          sig { override.returns({ arguments: String, name: String }) }
          def to_hash
          end
        end

        # A call to a function tool created by the model.
        #
        # Fields:
        #
        # - id (required): str
        # - type (required): Literal["function"]
        # - function (required): ChatCompletionMessageToolCallFunction
        # - thought_signature (optional): str
        module ToolCall
          extend DedalusSDK::Internal::Type::Union

          Variants =
            T.type_alias do
              T.any(
                DedalusSDK::Chat::ChatCompletionMessageToolCall,
                DedalusSDK::Chat::ChatCompletionMessageCustomToolCall
              )
            end

          sig do
            override.returns(
              T::Array[
                DedalusSDK::Chat::ChatCompletionAssistantMessageParam::ToolCall::Variants
              ]
            )
          end
          def self.variants
          end
        end
      end
    end
  end
end
