# typed: strong

module DedalusSDK
  module Models
    ChatCompletionMessage = Chat::ChatCompletionMessage

    module Chat
      class ChatCompletionMessage < DedalusSDK::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              DedalusSDK::Chat::ChatCompletionMessage,
              DedalusSDK::Internal::AnyHash
            )
          end

        # The contents of the message.
        sig { returns(T.nilable(String)) }
        attr_accessor :content

        # The refusal message generated by the model.
        sig { returns(T.nilable(String)) }
        attr_accessor :refusal

        # The role of the author of this message.
        sig { returns(Symbol) }
        attr_accessor :role

        # Annotations for the message, when applicable, as when using the
        # [web search tool](/docs/guides/tools-web-search?api-mode=chat).
        sig do
          returns(
            T.nilable(
              T::Array[DedalusSDK::Chat::ChatCompletionMessage::Annotation]
            )
          )
        end
        attr_reader :annotations

        sig do
          params(
            annotations:
              T::Array[
                DedalusSDK::Chat::ChatCompletionMessage::Annotation::OrHash
              ]
          ).void
        end
        attr_writer :annotations

        # If the audio output modality is requested, this object contains data about the
        # audio response from the model. [Learn more](/docs/guides/audio).
        #
        # Fields:
        #
        # - id (required): str
        # - expires_at (required): int
        # - data (required): str
        # - transcript (required): str
        sig do
          returns(T.nilable(DedalusSDK::Chat::ChatCompletionMessage::Audio))
        end
        attr_reader :audio

        sig do
          params(
            audio:
              T.nilable(DedalusSDK::Chat::ChatCompletionMessage::Audio::OrHash)
          ).void
        end
        attr_writer :audio

        # Deprecated and replaced by `tool_calls`. The name and arguments of a function
        # that should be called, as generated by the model.
        #
        # Fields:
        #
        # - arguments (required): str
        # - name (required): str
        sig do
          returns(
            T.nilable(DedalusSDK::Chat::ChatCompletionMessage::FunctionCall)
          )
        end
        attr_reader :function_call

        sig do
          params(
            function_call:
              DedalusSDK::Chat::ChatCompletionMessage::FunctionCall::OrHash
          ).void
        end
        attr_writer :function_call

        # The tool calls generated by the model, such as function calls.
        sig do
          returns(
            T.nilable(
              T::Array[
                DedalusSDK::Chat::ChatCompletionMessage::ToolCall::Variants
              ]
            )
          )
        end
        attr_reader :tool_calls

        sig do
          params(
            tool_calls:
              T::Array[
                T.any(
                  DedalusSDK::Chat::ChatCompletionMessageToolCall::OrHash,
                  DedalusSDK::Chat::ChatCompletionMessageCustomToolCall::OrHash
                )
              ]
          ).void
        end
        attr_writer :tool_calls

        # A chat completion message generated by the model.
        #
        # Fields:
        #
        # - content (required): str | None
        # - refusal (required): str | None
        # - tool_calls (optional): ChatCompletionMessageToolCalls
        # - annotations (optional): list[AnnotationsItem]
        # - role (required): Literal["assistant"]
        # - function_call (optional): ChatCompletionResponseMessageFunctionCall
        # - audio (optional): ChatCompletionResponseMessageAudio | None
        sig do
          params(
            content: T.nilable(String),
            refusal: T.nilable(String),
            annotations:
              T::Array[
                DedalusSDK::Chat::ChatCompletionMessage::Annotation::OrHash
              ],
            audio:
              T.nilable(DedalusSDK::Chat::ChatCompletionMessage::Audio::OrHash),
            function_call:
              DedalusSDK::Chat::ChatCompletionMessage::FunctionCall::OrHash,
            tool_calls:
              T::Array[
                T.any(
                  DedalusSDK::Chat::ChatCompletionMessageToolCall::OrHash,
                  DedalusSDK::Chat::ChatCompletionMessageCustomToolCall::OrHash
                )
              ],
            role: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The contents of the message.
          content:,
          # The refusal message generated by the model.
          refusal:,
          # Annotations for the message, when applicable, as when using the
          # [web search tool](/docs/guides/tools-web-search?api-mode=chat).
          annotations: nil,
          # If the audio output modality is requested, this object contains data about the
          # audio response from the model. [Learn more](/docs/guides/audio).
          #
          # Fields:
          #
          # - id (required): str
          # - expires_at (required): int
          # - data (required): str
          # - transcript (required): str
          audio: nil,
          # Deprecated and replaced by `tool_calls`. The name and arguments of a function
          # that should be called, as generated by the model.
          #
          # Fields:
          #
          # - arguments (required): str
          # - name (required): str
          function_call: nil,
          # The tool calls generated by the model, such as function calls.
          tool_calls: nil,
          # The role of the author of this message.
          role: :assistant
        )
        end

        sig do
          override.returns(
            {
              content: T.nilable(String),
              refusal: T.nilable(String),
              role: Symbol,
              annotations:
                T::Array[DedalusSDK::Chat::ChatCompletionMessage::Annotation],
              audio: T.nilable(DedalusSDK::Chat::ChatCompletionMessage::Audio),
              function_call:
                DedalusSDK::Chat::ChatCompletionMessage::FunctionCall,
              tool_calls:
                T::Array[
                  DedalusSDK::Chat::ChatCompletionMessage::ToolCall::Variants
                ]
            }
          )
        end
        def to_hash
        end

        class Annotation < DedalusSDK::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                DedalusSDK::Chat::ChatCompletionMessage::Annotation,
                DedalusSDK::Internal::AnyHash
              )
            end

          # The type of the URL citation. Always `url_citation`.
          sig { returns(Symbol) }
          attr_accessor :type

          # A URL citation when using web search.
          #
          # Fields:
          #
          # - end_index (required): int
          # - start_index (required): int
          # - url (required): str
          # - title (required): str
          sig do
            returns(
              DedalusSDK::Chat::ChatCompletionMessage::Annotation::URLCitation
            )
          end
          attr_reader :url_citation

          sig do
            params(
              url_citation:
                DedalusSDK::Chat::ChatCompletionMessage::Annotation::URLCitation::OrHash
            ).void
          end
          attr_writer :url_citation

          # A URL citation when using web search.
          #
          # Fields:
          #
          # - type (required): Literal["url_citation"]
          # - url_citation (required): UrlCitation
          sig do
            params(
              url_citation:
                DedalusSDK::Chat::ChatCompletionMessage::Annotation::URLCitation::OrHash,
              type: Symbol
            ).returns(T.attached_class)
          end
          def self.new(
            # A URL citation when using web search.
            #
            # Fields:
            #
            # - end_index (required): int
            # - start_index (required): int
            # - url (required): str
            # - title (required): str
            url_citation:,
            # The type of the URL citation. Always `url_citation`.
            type: :url_citation
          )
          end

          sig do
            override.returns(
              {
                type: Symbol,
                url_citation:
                  DedalusSDK::Chat::ChatCompletionMessage::Annotation::URLCitation
              }
            )
          end
          def to_hash
          end

          class URLCitation < DedalusSDK::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  DedalusSDK::Chat::ChatCompletionMessage::Annotation::URLCitation,
                  DedalusSDK::Internal::AnyHash
                )
              end

            # The index of the last character of the URL citation in the message.
            sig { returns(Integer) }
            attr_accessor :end_index

            # The index of the first character of the URL citation in the message.
            sig { returns(Integer) }
            attr_accessor :start_index

            # The title of the web resource.
            sig { returns(String) }
            attr_accessor :title

            # The URL of the web resource.
            sig { returns(String) }
            attr_accessor :url

            # A URL citation when using web search.
            #
            # Fields:
            #
            # - end_index (required): int
            # - start_index (required): int
            # - url (required): str
            # - title (required): str
            sig do
              params(
                end_index: Integer,
                start_index: Integer,
                title: String,
                url: String
              ).returns(T.attached_class)
            end
            def self.new(
              # The index of the last character of the URL citation in the message.
              end_index:,
              # The index of the first character of the URL citation in the message.
              start_index:,
              # The title of the web resource.
              title:,
              # The URL of the web resource.
              url:
            )
            end

            sig do
              override.returns(
                {
                  end_index: Integer,
                  start_index: Integer,
                  title: String,
                  url: String
                }
              )
            end
            def to_hash
            end
          end
        end

        class Audio < DedalusSDK::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                DedalusSDK::Chat::ChatCompletionMessage::Audio,
                DedalusSDK::Internal::AnyHash
              )
            end

          # Unique identifier for this audio response.
          sig { returns(String) }
          attr_accessor :id

          # Base64 encoded audio bytes generated by the model, in the format specified in
          # the request.
          sig { returns(String) }
          attr_accessor :data

          # The Unix timestamp (in seconds) for when this audio response will no longer be
          # accessible on the server for use in multi-turn conversations.
          sig { returns(Integer) }
          attr_accessor :expires_at

          # Transcript of the audio generated by the model.
          sig { returns(String) }
          attr_accessor :transcript

          # If the audio output modality is requested, this object contains data about the
          # audio response from the model. [Learn more](/docs/guides/audio).
          #
          # Fields:
          #
          # - id (required): str
          # - expires_at (required): int
          # - data (required): str
          # - transcript (required): str
          sig do
            params(
              id: String,
              data: String,
              expires_at: Integer,
              transcript: String
            ).returns(T.attached_class)
          end
          def self.new(
            # Unique identifier for this audio response.
            id:,
            # Base64 encoded audio bytes generated by the model, in the format specified in
            # the request.
            data:,
            # The Unix timestamp (in seconds) for when this audio response will no longer be
            # accessible on the server for use in multi-turn conversations.
            expires_at:,
            # Transcript of the audio generated by the model.
            transcript:
          )
          end

          sig do
            override.returns(
              {
                id: String,
                data: String,
                expires_at: Integer,
                transcript: String
              }
            )
          end
          def to_hash
          end
        end

        class FunctionCall < DedalusSDK::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                DedalusSDK::Chat::ChatCompletionMessage::FunctionCall,
                DedalusSDK::Internal::AnyHash
              )
            end

          # The arguments to call the function with, as generated by the model in JSON
          # format. Note that the model does not always generate valid JSON, and may
          # hallucinate parameters not defined by your function schema. Validate the
          # arguments in your code before calling your function.
          sig { returns(String) }
          attr_accessor :arguments

          # The name of the function to call.
          sig { returns(String) }
          attr_accessor :name

          # Deprecated and replaced by `tool_calls`. The name and arguments of a function
          # that should be called, as generated by the model.
          #
          # Fields:
          #
          # - arguments (required): str
          # - name (required): str
          sig do
            params(arguments: String, name: String).returns(T.attached_class)
          end
          def self.new(
            # The arguments to call the function with, as generated by the model in JSON
            # format. Note that the model does not always generate valid JSON, and may
            # hallucinate parameters not defined by your function schema. Validate the
            # arguments in your code before calling your function.
            arguments:,
            # The name of the function to call.
            name:
          )
          end

          sig { override.returns({ arguments: String, name: String }) }
          def to_hash
          end
        end

        # A call to a function tool created by the model.
        #
        # Fields:
        #
        # - id (required): str
        # - type (required): Literal["function"]
        # - function (required): ChatCompletionMessageToolCallFunction
        # - thought_signature (optional): str
        module ToolCall
          extend DedalusSDK::Internal::Type::Union

          Variants =
            T.type_alias do
              T.any(
                DedalusSDK::Chat::ChatCompletionMessageToolCall,
                DedalusSDK::Chat::ChatCompletionMessageCustomToolCall
              )
            end

          sig do
            override.returns(
              T::Array[
                DedalusSDK::Chat::ChatCompletionMessage::ToolCall::Variants
              ]
            )
          end
          def self.variants
          end
        end
      end
    end
  end
end
