# typed: strong

module DedalusSDK
  module Models
    ChatCompletionContentPartRefusalParam =
      Chat::ChatCompletionContentPartRefusalParam

    module Chat
      class ChatCompletionContentPartRefusalParam < DedalusSDK::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              DedalusSDK::Chat::ChatCompletionContentPartRefusalParam,
              DedalusSDK::Internal::AnyHash
            )
          end

        # The refusal message generated by the model.
        sig { returns(String) }
        attr_accessor :refusal

        # The type of the content part.
        sig { returns(Symbol) }
        attr_accessor :type

        # Schema for ChatCompletionRequestMessageContentPartRefusal.
        #
        # Fields:
        #
        # - type (required): Literal["refusal"]
        # - refusal (required): str
        sig { params(refusal: String, type: Symbol).returns(T.attached_class) }
        def self.new(
          # The refusal message generated by the model.
          refusal:,
          # The type of the content part.
          type: :refusal
        )
        end

        sig { override.returns({ refusal: String, type: Symbol }) }
        def to_hash
        end
      end
    end
  end
end
