# typed: strong

module DedalusSDK
  module Models
    ChatCompletionMessageToolCall = Chat::ChatCompletionMessageToolCall

    module Chat
      class ChatCompletionMessageToolCall < DedalusSDK::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              DedalusSDK::Chat::ChatCompletionMessageToolCall,
              DedalusSDK::Internal::AnyHash
            )
          end

        # The ID of the tool call.
        sig { returns(String) }
        attr_accessor :id

        # The function that the model called.
        #
        # Fields:
        #
        # - name (required): str
        # - arguments (required): str
        sig do
          returns(DedalusSDK::Chat::ChatCompletionMessageToolCall::Function)
        end
        attr_reader :function

        sig do
          params(
            function:
              DedalusSDK::Chat::ChatCompletionMessageToolCall::Function::OrHash
          ).void
        end
        attr_writer :function

        # The type of the tool. Currently, only `function` is supported.
        sig { returns(Symbol) }
        attr_accessor :type

        # Opaque signature for thought continuity in multi-turn tool use (Google-specific,
        # base64 encoded)
        sig { returns(T.nilable(String)) }
        attr_accessor :thought_signature

        # A call to a function tool created by the model.
        #
        # Fields:
        #
        # - id (required): str
        # - type (required): Literal["function"]
        # - function (required): ChatCompletionMessageToolCallFunction
        # - thought_signature (optional): str
        sig do
          params(
            id: String,
            function:
              DedalusSDK::Chat::ChatCompletionMessageToolCall::Function::OrHash,
            thought_signature: T.nilable(String),
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The ID of the tool call.
          id:,
          # The function that the model called.
          #
          # Fields:
          #
          # - name (required): str
          # - arguments (required): str
          function:,
          # Opaque signature for thought continuity in multi-turn tool use (Google-specific,
          # base64 encoded)
          thought_signature: nil,
          # The type of the tool. Currently, only `function` is supported.
          type: :function
        )
        end

        sig do
          override.returns(
            {
              id: String,
              function:
                DedalusSDK::Chat::ChatCompletionMessageToolCall::Function,
              type: Symbol,
              thought_signature: T.nilable(String)
            }
          )
        end
        def to_hash
        end

        class Function < DedalusSDK::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                DedalusSDK::Chat::ChatCompletionMessageToolCall::Function,
                DedalusSDK::Internal::AnyHash
              )
            end

          # The arguments to call the function with, as generated by the model in JSON
          # format. Note that the model does not always generate valid JSON, and may
          # hallucinate parameters not defined by your function schema. Validate the
          # arguments in your code before calling your function.
          sig { returns(String) }
          attr_accessor :arguments

          # The name of the function to call.
          sig { returns(String) }
          attr_accessor :name

          # The function that the model called.
          #
          # Fields:
          #
          # - name (required): str
          # - arguments (required): str
          sig do
            params(arguments: String, name: String).returns(T.attached_class)
          end
          def self.new(
            # The arguments to call the function with, as generated by the model in JSON
            # format. Note that the model does not always generate valid JSON, and may
            # hallucinate parameters not defined by your function schema. Validate the
            # arguments in your code before calling your function.
            arguments:,
            # The name of the function to call.
            name:
          )
          end

          sig { override.returns({ arguments: String, name: String }) }
          def to_hash
          end
        end
      end
    end
  end
end
