# typed: strong

module DedalusSDK
  module Models
    module Chat
      class Choice < DedalusSDK::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(DedalusSDK::Chat::Choice, DedalusSDK::Internal::AnyHash)
          end

        # The index of the choice in the list of choices.
        sig { returns(Integer) }
        attr_accessor :index

        # A chat completion message generated by the model.
        sig { returns(DedalusSDK::Chat::ChatCompletionMessage) }
        attr_reader :message

        sig do
          params(message: DedalusSDK::Chat::ChatCompletionMessage::OrHash).void
        end
        attr_writer :message

        # The reason the model stopped generating tokens. This will be `stop` if the model
        # hit a natural stop point or a provided stop sequence, `length` if the maximum
        # number of tokens specified in the request was reached, `content_filter` if
        # content was omitted due to a flag from our content filters, `tool_calls` if the
        # model called a tool, or `function_call` (deprecated) if the model called a
        # function.
        sig do
          returns(
            T.nilable(DedalusSDK::Chat::Choice::FinishReason::TaggedSymbol)
          )
        end
        attr_accessor :finish_reason

        # Log probability information for the choice.
        sig { returns(T.nilable(DedalusSDK::Chat::ChoiceLogprobs)) }
        attr_reader :logprobs

        sig do
          params(
            logprobs: T.nilable(DedalusSDK::Chat::ChoiceLogprobs::OrHash)
          ).void
        end
        attr_writer :logprobs

        # A chat completion choice.
        #
        # OpenAI-compatible choice object for non-streaming responses. Part of the
        # ChatCompletion response.
        sig do
          params(
            index: Integer,
            message: DedalusSDK::Chat::ChatCompletionMessage::OrHash,
            finish_reason:
              T.nilable(DedalusSDK::Chat::Choice::FinishReason::OrSymbol),
            logprobs: T.nilable(DedalusSDK::Chat::ChoiceLogprobs::OrHash)
          ).returns(T.attached_class)
        end
        def self.new(
          # The index of the choice in the list of choices.
          index:,
          # A chat completion message generated by the model.
          message:,
          # The reason the model stopped generating tokens. This will be `stop` if the model
          # hit a natural stop point or a provided stop sequence, `length` if the maximum
          # number of tokens specified in the request was reached, `content_filter` if
          # content was omitted due to a flag from our content filters, `tool_calls` if the
          # model called a tool, or `function_call` (deprecated) if the model called a
          # function.
          finish_reason: nil,
          # Log probability information for the choice.
          logprobs: nil
        )
        end

        sig do
          override.returns(
            {
              index: Integer,
              message: DedalusSDK::Chat::ChatCompletionMessage,
              finish_reason:
                T.nilable(DedalusSDK::Chat::Choice::FinishReason::TaggedSymbol),
              logprobs: T.nilable(DedalusSDK::Chat::ChoiceLogprobs)
            }
          )
        end
        def to_hash
        end

        # The reason the model stopped generating tokens. This will be `stop` if the model
        # hit a natural stop point or a provided stop sequence, `length` if the maximum
        # number of tokens specified in the request was reached, `content_filter` if
        # content was omitted due to a flag from our content filters, `tool_calls` if the
        # model called a tool, or `function_call` (deprecated) if the model called a
        # function.
        module FinishReason
          extend DedalusSDK::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(Symbol, DedalusSDK::Chat::Choice::FinishReason)
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          STOP =
            T.let(:stop, DedalusSDK::Chat::Choice::FinishReason::TaggedSymbol)
          LENGTH =
            T.let(:length, DedalusSDK::Chat::Choice::FinishReason::TaggedSymbol)
          TOOL_CALLS =
            T.let(
              :tool_calls,
              DedalusSDK::Chat::Choice::FinishReason::TaggedSymbol
            )
          CONTENT_FILTER =
            T.let(
              :content_filter,
              DedalusSDK::Chat::Choice::FinishReason::TaggedSymbol
            )
          FUNCTION_CALL =
            T.let(
              :function_call,
              DedalusSDK::Chat::Choice::FinishReason::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[DedalusSDK::Chat::Choice::FinishReason::TaggedSymbol]
            )
          end
          def self.values
          end
        end
      end
    end
  end
end
