# typed: strong

module DedalusSDK
  module Models
    module Chat
      class ChoiceDelta < DedalusSDK::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(DedalusSDK::Chat::ChoiceDelta, DedalusSDK::Internal::AnyHash)
          end

        # The contents of the chunk message.
        sig { returns(T.nilable(String)) }
        attr_accessor :content

        # Deprecated and replaced by `tool_calls`. The name and arguments of a function
        # that should be called, as generated by the model.
        #
        # Fields:
        #
        # - arguments (optional): str
        # - name (optional): str
        sig { returns(T.nilable(DedalusSDK::Chat::ChoiceDelta::FunctionCall)) }
        attr_reader :function_call

        sig do
          params(
            function_call: DedalusSDK::Chat::ChoiceDelta::FunctionCall::OrHash
          ).void
        end
        attr_writer :function_call

        # The refusal message generated by the model.
        sig { returns(T.nilable(String)) }
        attr_accessor :refusal

        # The role of the author of this message.
        sig do
          returns(T.nilable(DedalusSDK::Chat::ChoiceDelta::Role::TaggedSymbol))
        end
        attr_reader :role

        sig { params(role: DedalusSDK::Chat::ChoiceDelta::Role::OrSymbol).void }
        attr_writer :role

        sig do
          returns(T.nilable(T::Array[DedalusSDK::Chat::ChoiceDeltaToolCall]))
        end
        attr_reader :tool_calls

        sig do
          params(
            tool_calls: T::Array[DedalusSDK::Chat::ChoiceDeltaToolCall::OrHash]
          ).void
        end
        attr_writer :tool_calls

        # A chat completion delta generated by streamed model responses.
        #
        # Fields:
        #
        # - content (optional): str | None
        # - function_call (optional): ChatCompletionStreamResponseDeltaFunctionCall
        # - tool_calls (optional): list[ChatCompletionMessageToolCallChunk]
        # - role (optional): Literal["developer", "system", "user", "assistant", "tool"]
        # - refusal (optional): str | None
        sig do
          params(
            content: T.nilable(String),
            function_call: DedalusSDK::Chat::ChoiceDelta::FunctionCall::OrHash,
            refusal: T.nilable(String),
            role: DedalusSDK::Chat::ChoiceDelta::Role::OrSymbol,
            tool_calls: T::Array[DedalusSDK::Chat::ChoiceDeltaToolCall::OrHash]
          ).returns(T.attached_class)
        end
        def self.new(
          # The contents of the chunk message.
          content: nil,
          # Deprecated and replaced by `tool_calls`. The name and arguments of a function
          # that should be called, as generated by the model.
          #
          # Fields:
          #
          # - arguments (optional): str
          # - name (optional): str
          function_call: nil,
          # The refusal message generated by the model.
          refusal: nil,
          # The role of the author of this message.
          role: nil,
          tool_calls: nil
        )
        end

        sig do
          override.returns(
            {
              content: T.nilable(String),
              function_call: DedalusSDK::Chat::ChoiceDelta::FunctionCall,
              refusal: T.nilable(String),
              role: DedalusSDK::Chat::ChoiceDelta::Role::TaggedSymbol,
              tool_calls: T::Array[DedalusSDK::Chat::ChoiceDeltaToolCall]
            }
          )
        end
        def to_hash
        end

        class FunctionCall < DedalusSDK::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                DedalusSDK::Chat::ChoiceDelta::FunctionCall,
                DedalusSDK::Internal::AnyHash
              )
            end

          # The arguments to call the function with, as generated by the model in JSON
          # format. Note that the model does not always generate valid JSON, and may
          # hallucinate parameters not defined by your function schema. Validate the
          # arguments in your code before calling your function.
          sig { returns(T.nilable(String)) }
          attr_reader :arguments

          sig { params(arguments: String).void }
          attr_writer :arguments

          # The name of the function to call.
          sig { returns(T.nilable(String)) }
          attr_reader :name

          sig { params(name: String).void }
          attr_writer :name

          # Deprecated and replaced by `tool_calls`. The name and arguments of a function
          # that should be called, as generated by the model.
          #
          # Fields:
          #
          # - arguments (optional): str
          # - name (optional): str
          sig do
            params(arguments: String, name: String).returns(T.attached_class)
          end
          def self.new(
            # The arguments to call the function with, as generated by the model in JSON
            # format. Note that the model does not always generate valid JSON, and may
            # hallucinate parameters not defined by your function schema. Validate the
            # arguments in your code before calling your function.
            arguments: nil,
            # The name of the function to call.
            name: nil
          )
          end

          sig { override.returns({ arguments: String, name: String }) }
          def to_hash
          end
        end

        # The role of the author of this message.
        module Role
          extend DedalusSDK::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias { T.all(Symbol, DedalusSDK::Chat::ChoiceDelta::Role) }
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          DEVELOPER =
            T.let(:developer, DedalusSDK::Chat::ChoiceDelta::Role::TaggedSymbol)
          SYSTEM =
            T.let(:system, DedalusSDK::Chat::ChoiceDelta::Role::TaggedSymbol)
          USER = T.let(:user, DedalusSDK::Chat::ChoiceDelta::Role::TaggedSymbol)
          ASSISTANT =
            T.let(:assistant, DedalusSDK::Chat::ChoiceDelta::Role::TaggedSymbol)
          TOOL = T.let(:tool, DedalusSDK::Chat::ChoiceDelta::Role::TaggedSymbol)

          sig do
            override.returns(
              T::Array[DedalusSDK::Chat::ChoiceDelta::Role::TaggedSymbol]
            )
          end
          def self.values
          end
        end
      end
    end
  end
end
