# typed: strong

module DedalusSDK
  module Models
    module Chat
      class ChoiceDeltaToolCall < DedalusSDK::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              DedalusSDK::Chat::ChoiceDeltaToolCall,
              DedalusSDK::Internal::AnyHash
            )
          end

        sig { returns(Integer) }
        attr_accessor :index

        # The ID of the tool call.
        sig { returns(T.nilable(String)) }
        attr_reader :id

        sig { params(id: String).void }
        attr_writer :id

        # Schema for ChatCompletionMessageToolCallChunkFunction.
        #
        # Fields:
        #
        # - name (optional): str
        # - arguments (optional): str
        sig do
          returns(T.nilable(DedalusSDK::Chat::ChoiceDeltaToolCall::Function))
        end
        attr_reader :function

        sig do
          params(
            function: DedalusSDK::Chat::ChoiceDeltaToolCall::Function::OrHash
          ).void
        end
        attr_writer :function

        # The type of the tool. Currently, only `function` is supported.
        sig do
          returns(
            T.nilable(DedalusSDK::Chat::ChoiceDeltaToolCall::Type::TaggedSymbol)
          )
        end
        attr_reader :type

        sig do
          params(
            type: DedalusSDK::Chat::ChoiceDeltaToolCall::Type::OrSymbol
          ).void
        end
        attr_writer :type

        # Schema for ChatCompletionMessageToolCallChunk.
        #
        # Fields:
        #
        # - index (required): int
        # - id (optional): str
        # - type (optional): Literal["function"]
        # - function (optional): ChatCompletionMessageToolCallChunkFunction
        sig do
          params(
            index: Integer,
            id: String,
            function: DedalusSDK::Chat::ChoiceDeltaToolCall::Function::OrHash,
            type: DedalusSDK::Chat::ChoiceDeltaToolCall::Type::OrSymbol
          ).returns(T.attached_class)
        end
        def self.new(
          index:,
          # The ID of the tool call.
          id: nil,
          # Schema for ChatCompletionMessageToolCallChunkFunction.
          #
          # Fields:
          #
          # - name (optional): str
          # - arguments (optional): str
          function: nil,
          # The type of the tool. Currently, only `function` is supported.
          type: nil
        )
        end

        sig do
          override.returns(
            {
              index: Integer,
              id: String,
              function: DedalusSDK::Chat::ChoiceDeltaToolCall::Function,
              type: DedalusSDK::Chat::ChoiceDeltaToolCall::Type::TaggedSymbol
            }
          )
        end
        def to_hash
        end

        class Function < DedalusSDK::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                DedalusSDK::Chat::ChoiceDeltaToolCall::Function,
                DedalusSDK::Internal::AnyHash
              )
            end

          # The arguments to call the function with, as generated by the model in JSON
          # format. Note that the model does not always generate valid JSON, and may
          # hallucinate parameters not defined by your function schema. Validate the
          # arguments in your code before calling your function.
          sig { returns(T.nilable(String)) }
          attr_reader :arguments

          sig { params(arguments: String).void }
          attr_writer :arguments

          # The name of the function to call.
          sig { returns(T.nilable(String)) }
          attr_reader :name

          sig { params(name: String).void }
          attr_writer :name

          # Schema for ChatCompletionMessageToolCallChunkFunction.
          #
          # Fields:
          #
          # - name (optional): str
          # - arguments (optional): str
          sig do
            params(arguments: String, name: String).returns(T.attached_class)
          end
          def self.new(
            # The arguments to call the function with, as generated by the model in JSON
            # format. Note that the model does not always generate valid JSON, and may
            # hallucinate parameters not defined by your function schema. Validate the
            # arguments in your code before calling your function.
            arguments: nil,
            # The name of the function to call.
            name: nil
          )
          end

          sig { override.returns({ arguments: String, name: String }) }
          def to_hash
          end
        end

        # The type of the tool. Currently, only `function` is supported.
        module Type
          extend DedalusSDK::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(Symbol, DedalusSDK::Chat::ChoiceDeltaToolCall::Type)
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          FUNCTION =
            T.let(
              :function,
              DedalusSDK::Chat::ChoiceDeltaToolCall::Type::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                DedalusSDK::Chat::ChoiceDeltaToolCall::Type::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end
      end
    end
  end
end
