# typed: strong

module DedalusSDK
  module Models
    module Chat
      class CompletionTokensDetails < DedalusSDK::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              DedalusSDK::Chat::CompletionTokensDetails,
              DedalusSDK::Internal::AnyHash
            )
          end

        # When using Predicted Outputs, the number of tokens in the prediction that
        # appeared in the completion.
        sig { returns(T.nilable(Integer)) }
        attr_reader :accepted_prediction_tokens

        sig { params(accepted_prediction_tokens: Integer).void }
        attr_writer :accepted_prediction_tokens

        # Audio input tokens generated by the model.
        sig { returns(T.nilable(Integer)) }
        attr_reader :audio_tokens

        sig { params(audio_tokens: Integer).void }
        attr_writer :audio_tokens

        # Tokens generated by the model for reasoning.
        sig { returns(T.nilable(Integer)) }
        attr_reader :reasoning_tokens

        sig { params(reasoning_tokens: Integer).void }
        attr_writer :reasoning_tokens

        # When using Predicted Outputs, the number of tokens in the prediction that did
        # not appear in the completion. However, like reasoning tokens, these tokens are
        # still counted in the total completion tokens for purposes of billing, output,
        # and context window limits.
        sig { returns(T.nilable(Integer)) }
        attr_reader :rejected_prediction_tokens

        sig { params(rejected_prediction_tokens: Integer).void }
        attr_writer :rejected_prediction_tokens

        # Breakdown of tokens used in a completion.
        #
        # Fields:
        #
        # - accepted_prediction_tokens (optional): int
        # - audio_tokens (optional): int
        # - reasoning_tokens (optional): int
        # - rejected_prediction_tokens (optional): int
        sig do
          params(
            accepted_prediction_tokens: Integer,
            audio_tokens: Integer,
            reasoning_tokens: Integer,
            rejected_prediction_tokens: Integer
          ).returns(T.attached_class)
        end
        def self.new(
          # When using Predicted Outputs, the number of tokens in the prediction that
          # appeared in the completion.
          accepted_prediction_tokens: nil,
          # Audio input tokens generated by the model.
          audio_tokens: nil,
          # Tokens generated by the model for reasoning.
          reasoning_tokens: nil,
          # When using Predicted Outputs, the number of tokens in the prediction that did
          # not appear in the completion. However, like reasoning tokens, these tokens are
          # still counted in the total completion tokens for purposes of billing, output,
          # and context window limits.
          rejected_prediction_tokens: nil
        )
        end

        sig do
          override.returns(
            {
              accepted_prediction_tokens: Integer,
              audio_tokens: Integer,
              reasoning_tokens: Integer,
              rejected_prediction_tokens: Integer
            }
          )
        end
        def to_hash
        end
      end
    end
  end
end
