# typed: strong

module DedalusSDK
  module Models
    module Chat
      class StreamChoice < DedalusSDK::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(DedalusSDK::Chat::StreamChoice, DedalusSDK::Internal::AnyHash)
          end

        # A chat completion delta generated by streamed model responses.
        sig { returns(DedalusSDK::Chat::ChoiceDelta) }
        attr_reader :delta

        sig { params(delta: DedalusSDK::Chat::ChoiceDelta::OrHash).void }
        attr_writer :delta

        # The reason the model stopped generating tokens. This will be `stop` if the model
        # hit a natural stop point or a provided stop sequence, `length` if the maximum
        # number of tokens specified in the request was reached, `content_filter` if
        # content was omitted due to a flag from our content filters, `tool_calls` if the
        # model called a tool, or `function_call` (deprecated) if the model called a
        # function.
        sig do
          returns(
            T.nilable(
              DedalusSDK::Chat::StreamChoice::FinishReason::TaggedSymbol
            )
          )
        end
        attr_accessor :finish_reason

        # The index of the choice in the list of choices.
        sig { returns(Integer) }
        attr_accessor :index

        # Log probability information for the choice.
        #
        # Fields:
        #
        # - content (required): list[ChatCompletionTokenLogprob]
        # - refusal (required): list[ChatCompletionTokenLogprob]
        sig { returns(T.nilable(DedalusSDK::Chat::StreamChoiceLogprobs)) }
        attr_reader :logprobs

        sig do
          params(
            logprobs: T.nilable(DedalusSDK::Chat::StreamChoiceLogprobs::OrHash)
          ).void
        end
        attr_writer :logprobs

        # Schema for ChatCompletionStreamResponseChoicesItem.
        #
        # Fields:
        #
        # - delta (required): ChatCompletionStreamResponseDelta
        # - logprobs (optional): ChatCompletionStreamResponseChoicesItemLogprobs
        # - finish_reason (required): Literal["stop", "length", "tool_calls",
        #   "content_filter", "function_call"]
        # - index (required): int
        sig do
          params(
            delta: DedalusSDK::Chat::ChoiceDelta::OrHash,
            finish_reason:
              T.nilable(DedalusSDK::Chat::StreamChoice::FinishReason::OrSymbol),
            index: Integer,
            logprobs: T.nilable(DedalusSDK::Chat::StreamChoiceLogprobs::OrHash)
          ).returns(T.attached_class)
        end
        def self.new(
          # A chat completion delta generated by streamed model responses.
          delta:,
          # The reason the model stopped generating tokens. This will be `stop` if the model
          # hit a natural stop point or a provided stop sequence, `length` if the maximum
          # number of tokens specified in the request was reached, `content_filter` if
          # content was omitted due to a flag from our content filters, `tool_calls` if the
          # model called a tool, or `function_call` (deprecated) if the model called a
          # function.
          finish_reason:,
          # The index of the choice in the list of choices.
          index:,
          # Log probability information for the choice.
          #
          # Fields:
          #
          # - content (required): list[ChatCompletionTokenLogprob]
          # - refusal (required): list[ChatCompletionTokenLogprob]
          logprobs: nil
        )
        end

        sig do
          override.returns(
            {
              delta: DedalusSDK::Chat::ChoiceDelta,
              finish_reason:
                T.nilable(
                  DedalusSDK::Chat::StreamChoice::FinishReason::TaggedSymbol
                ),
              index: Integer,
              logprobs: T.nilable(DedalusSDK::Chat::StreamChoiceLogprobs)
            }
          )
        end
        def to_hash
        end

        # The reason the model stopped generating tokens. This will be `stop` if the model
        # hit a natural stop point or a provided stop sequence, `length` if the maximum
        # number of tokens specified in the request was reached, `content_filter` if
        # content was omitted due to a flag from our content filters, `tool_calls` if the
        # model called a tool, or `function_call` (deprecated) if the model called a
        # function.
        module FinishReason
          extend DedalusSDK::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(Symbol, DedalusSDK::Chat::StreamChoice::FinishReason)
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          STOP =
            T.let(
              :stop,
              DedalusSDK::Chat::StreamChoice::FinishReason::TaggedSymbol
            )
          LENGTH =
            T.let(
              :length,
              DedalusSDK::Chat::StreamChoice::FinishReason::TaggedSymbol
            )
          TOOL_CALLS =
            T.let(
              :tool_calls,
              DedalusSDK::Chat::StreamChoice::FinishReason::TaggedSymbol
            )
          CONTENT_FILTER =
            T.let(
              :content_filter,
              DedalusSDK::Chat::StreamChoice::FinishReason::TaggedSymbol
            )
          FUNCTION_CALL =
            T.let(
              :function_call,
              DedalusSDK::Chat::StreamChoice::FinishReason::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                DedalusSDK::Chat::StreamChoice::FinishReason::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end
      end
    end
  end
end
