# frozen_string_literal: true

module DedalusSDK
  module Models
    # @see DedalusSDK::Resources::Embeddings#create
    class CreateEmbeddingResponse < DedalusSDK::Internal::Type::BaseModel
      # @!attribute data
      #   The list of embeddings generated by the model.
      #
      #   @return [Array<DedalusSDK::Models::CreateEmbeddingResponse::Data>]
      required :data, -> { DedalusSDK::Internal::Type::ArrayOf[DedalusSDK::CreateEmbeddingResponse::Data] }

      # @!attribute model
      #   The name of the model used to generate the embedding.
      #
      #   @return [String]
      required :model, String

      # @!attribute object
      #   The object type, which is always "list".
      #
      #   @return [Symbol, :list]
      required :object, const: :list

      # @!attribute usage
      #   The usage information for the request.
      #
      #   @return [DedalusSDK::Models::CreateEmbeddingResponse::Usage]
      required :usage, -> { DedalusSDK::CreateEmbeddingResponse::Usage }

      # @!method initialize(data:, model:, usage:, object: :list)
      #   Schema for EmbeddingResponse.
      #
      #   Fields:
      #
      #   - data (required): list[Embedding]
      #   - model (required): str
      #   - object (required): Literal["list"]
      #   - usage (required): Usage
      #
      #   @param data [Array<DedalusSDK::Models::CreateEmbeddingResponse::Data>] The list of embeddings generated by the model.
      #
      #   @param model [String] The name of the model used to generate the embedding.
      #
      #   @param usage [DedalusSDK::Models::CreateEmbeddingResponse::Usage] The usage information for the request.
      #
      #   @param object [Symbol, :list] The object type, which is always "list".

      class Data < DedalusSDK::Internal::Type::BaseModel
        # @!attribute embedding
        #   The embedding vector, which is a list of floats. The length of vector depends on
        #   the model as listed in the [embedding guide](/docs/guides/embeddings).
        #
        #   @return [Array<Float>]
        required :embedding, DedalusSDK::Internal::Type::ArrayOf[Float]

        # @!attribute index
        #   The index of the embedding in the list of embeddings.
        #
        #   @return [Integer]
        required :index, Integer

        # @!attribute object
        #   The object type, which is always "embedding".
        #
        #   @return [Symbol, :embedding]
        required :object, const: :embedding

        # @!method initialize(embedding:, index:, object: :embedding)
        #   Some parameter documentations has been truncated, see
        #   {DedalusSDK::Models::CreateEmbeddingResponse::Data} for more details.
        #
        #   Represents an embedding vector returned by embedding endpoint.
        #
        #   Fields:
        #
        #   - index (required): int
        #   - embedding (required): list[float]
        #   - object (required): Literal["embedding"]
        #
        #   @param embedding [Array<Float>] The embedding vector, which is a list of floats. The length of vector depends on
        #
        #   @param index [Integer] The index of the embedding in the list of embeddings.
        #
        #   @param object [Symbol, :embedding] The object type, which is always "embedding".
      end

      # @see DedalusSDK::Models::CreateEmbeddingResponse#usage
      class Usage < DedalusSDK::Internal::Type::BaseModel
        # @!attribute prompt_tokens
        #   The number of tokens used by the prompt.
        #
        #   @return [Integer]
        required :prompt_tokens, Integer

        # @!attribute total_tokens
        #   The total number of tokens used by the request.
        #
        #   @return [Integer]
        required :total_tokens, Integer

        # @!method initialize(prompt_tokens:, total_tokens:)
        #   The usage information for the request.
        #
        #   @param prompt_tokens [Integer] The number of tokens used by the prompt.
        #
        #   @param total_tokens [Integer] The total number of tokens used by the request.
      end
    end
  end
end
