# frozen_string_literal: true

module DedalusSDK
  module Models
    # @see DedalusSDK::Resources::Responses#create
    class Response < DedalusSDK::Internal::Type::BaseModel
      # @!attribute id
      #   Unique identifier for this Response
      #
      #   @return [String]
      required :id, String

      # @!attribute created_at
      #   Unix timestamp (in seconds) when this Response was created
      #
      #   @return [Float]
      required :created_at, Float

      # @!attribute model
      #   The model used for this response
      #
      #   @return [String]
      required :model, String

      # @!attribute output
      #   Array of content items generated by the model
      #
      #   @return [Array<Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}>]
      required :output,
               -> { DedalusSDK::Internal::Type::ArrayOf[DedalusSDK::Internal::Type::HashOf[union: DedalusSDK::JSONValueInput, nil?: true]] }

      # @!attribute status
      #   The status of the response generation
      #
      #   @return [Symbol, DedalusSDK::Models::Response::Status]
      required :status, enum: -> { DedalusSDK::Response::Status }

      # @!attribute background
      #   Whether the request was run in the background
      #
      #   @return [Boolean, nil]
      optional :background, DedalusSDK::Internal::Type::Boolean, nil?: true

      # @!attribute completed_at
      #   Unix timestamp (in seconds) when the response was completed
      #
      #   @return [Float, nil]
      optional :completed_at, Float, nil?: true

      # @!attribute conversation
      #   Conversation this response belongs to (requires BYOK)
      #
      #   @return [Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}, nil]
      optional :conversation,
               -> { DedalusSDK::Internal::Type::HashOf[union: DedalusSDK::JSONValueInput, nil?: true] },
               nil?: true

      # @!attribute error
      #   Error details if status is 'failed'
      #
      #   @return [Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}, nil]
      optional :error,
               -> { DedalusSDK::Internal::Type::HashOf[union: DedalusSDK::JSONValueInput, nil?: true] },
               nil?: true

      # @!attribute frequency_penalty
      #   Frequency penalty used for this response
      #
      #   @return [Float, nil]
      optional :frequency_penalty, Float, nil?: true

      # @!attribute incomplete_details
      #   Details about why the response is incomplete (e.g., max_output_tokens,
      #   content_filter)
      #
      #   @return [Hash{Symbol=>String}, nil]
      optional :incomplete_details, DedalusSDK::Internal::Type::HashOf[String], nil?: true

      # @!attribute instructions
      #   System/developer instructions used
      #
      #   @return [String, Array<Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}>, nil]
      optional :instructions, union: -> { DedalusSDK::Response::Instructions }, nil?: true

      # @!attribute max_output_tokens
      #   Maximum output tokens allowed for this response
      #
      #   @return [Integer, nil]
      optional :max_output_tokens, Integer, nil?: true

      # @!attribute max_tool_calls
      #   Maximum tool calls allowed for this response
      #
      #   @return [Integer, nil]
      optional :max_tool_calls, Integer, nil?: true

      # @!attribute mcp_server_errors
      #   MCP server failures keyed by server name.
      #
      #   @return [Hash{Symbol=>DedalusSDK::Models::Response::MCPServerError}, nil]
      optional :mcp_server_errors,
               -> { DedalusSDK::Internal::Type::HashOf[DedalusSDK::Response::MCPServerError] },
               nil?: true

      # @!attribute mcp_tool_results
      #   Results of MCP tool executions including inputs, outputs, and timing.
      #
      #   @return [Array<DedalusSDK::Models::MCPToolResult>, nil]
      optional :mcp_tool_results,
               -> { DedalusSDK::Internal::Type::ArrayOf[DedalusSDK::MCPToolResult] },
               nil?: true

      # @!attribute metadata
      #   Key-value pairs attached to this response (requires BYOK)
      #
      #   @return [Hash{Symbol=>String}, nil]
      optional :metadata, DedalusSDK::Internal::Type::HashOf[String], nil?: true

      # @!attribute object
      #   The object type, always 'response'
      #
      #   @return [Symbol, DedalusSDK::Models::Response::Object, nil]
      optional :object, enum: -> { DedalusSDK::Response::Object }

      # @!attribute output_text
      #   Aggregated text output from all output_text items (SDK-only convenience
      #   property)
      #
      #   @return [String, nil]
      optional :output_text, String, nil?: true

      # @!attribute parallel_tool_calls
      #   Whether parallel tool calls were enabled
      #
      #   @return [Boolean, nil]
      optional :parallel_tool_calls, DedalusSDK::Internal::Type::Boolean, nil?: true

      # @!attribute presence_penalty
      #   Presence penalty used for this response
      #
      #   @return [Float, nil]
      optional :presence_penalty, Float, nil?: true

      # @!attribute previous_response_id
      #   Previous response ID referenced, if any
      #
      #   @return [String, nil]
      optional :previous_response_id, String, nil?: true

      # @!attribute prompt_cache_key
      #   Prompt cache key used for this response
      #
      #   @return [String, nil]
      optional :prompt_cache_key, String, nil?: true

      # @!attribute reasoning
      #   Reasoning configuration and outputs
      #
      #   @return [Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}, nil]
      optional :reasoning,
               -> { DedalusSDK::Internal::Type::HashOf[union: DedalusSDK::JSONValueInput, nil?: true] },
               nil?: true

      # @!attribute safety_identifier
      #   Safety identifier used for this response
      #
      #   @return [String, nil]
      optional :safety_identifier, String, nil?: true

      # @!attribute service_tier
      #   Service tier used for this response
      #
      #   @return [String, nil]
      optional :service_tier, String, nil?: true

      # @!attribute store
      #   Whether the response was stored for later retrieval
      #
      #   @return [Boolean, nil]
      optional :store, DedalusSDK::Internal::Type::Boolean, nil?: true

      # @!attribute temperature
      #   Temperature parameter used
      #
      #   @return [Float, nil]
      optional :temperature, Float, nil?: true

      # @!attribute text
      #   Text configuration used for this response
      #
      #   @return [Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}, nil]
      optional :text,
               -> { DedalusSDK::Internal::Type::HashOf[union: DedalusSDK::JSONValueInput, nil?: true] },
               nil?: true

      # @!attribute tool_choice
      #   Tool choice configuration used
      #
      #   @return [String, Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}, nil]
      optional :tool_choice, union: -> { DedalusSDK::Response::ToolChoice }, nil?: true

      # @!attribute tools
      #   Tools that were available to the model
      #
      #   @return [Array<Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}>, nil]
      optional :tools,
               -> {
                 DedalusSDK::Internal::Type::ArrayOf[DedalusSDK::Internal::Type::HashOf[union: DedalusSDK::JSONValueInput,
                                                                                        nil?: true]]
               },
               nil?: true

      # @!attribute tools_executed
      #   List of tool names that were executed server-side (e.g., MCP tools).
      #
      #   @return [Array<String>, nil]
      optional :tools_executed, DedalusSDK::Internal::Type::ArrayOf[String], nil?: true

      # @!attribute top_logprobs
      #   Number of logprob tokens returned per position
      #
      #   @return [Integer, nil]
      optional :top_logprobs, Integer, nil?: true

      # @!attribute top_p
      #   Top-p parameter used
      #
      #   @return [Float, nil]
      optional :top_p, Float, nil?: true

      # @!attribute truncation
      #   Truncation strategy applied when context exceeded limits
      #
      #   @return [String, nil]
      optional :truncation, String, nil?: true

      # @!attribute usage
      #   Token usage statistics for the response
      #
      #   @return [Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}, nil]
      optional :usage,
               -> { DedalusSDK::Internal::Type::HashOf[union: DedalusSDK::JSONValueInput, nil?: true] },
               nil?: true

      # @!method initialize(id:, created_at:, model:, output:, status:, background: nil, completed_at: nil, conversation: nil, error: nil, frequency_penalty: nil, incomplete_details: nil, instructions: nil, max_output_tokens: nil, max_tool_calls: nil, mcp_server_errors: nil, mcp_tool_results: nil, metadata: nil, object: nil, output_text: nil, parallel_tool_calls: nil, presence_penalty: nil, previous_response_id: nil, prompt_cache_key: nil, reasoning: nil, safety_identifier: nil, service_tier: nil, store: nil, temperature: nil, text: nil, tool_choice: nil, tools: nil, tools_executed: nil, top_logprobs: nil, top_p: nil, truncation: nil, usage: nil)
      #   Some parameter documentations has been truncated, see
      #   {DedalusSDK::Models::Response} for more details.
      #
      #   Responses API response with Dedalus extensions.
      #
      #   @param id [String] Unique identifier for this Response
      #
      #   @param created_at [Float] Unix timestamp (in seconds) when this Response was created
      #
      #   @param model [String] The model used for this response
      #
      #   @param output [Array<Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}>] Array of content items generated by the model
      #
      #   @param status [Symbol, DedalusSDK::Models::Response::Status] The status of the response generation
      #
      #   @param background [Boolean, nil] Whether the request was run in the background
      #
      #   @param completed_at [Float, nil] Unix timestamp (in seconds) when the response was completed
      #
      #   @param conversation [Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}, nil] Conversation this response belongs to (requires BYOK)
      #
      #   @param error [Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}, nil] Error details if status is 'failed'
      #
      #   @param frequency_penalty [Float, nil] Frequency penalty used for this response
      #
      #   @param incomplete_details [Hash{Symbol=>String}, nil] Details about why the response is incomplete (e.g., max_output_tokens, content_f
      #
      #   @param instructions [String, Array<Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}>, nil] System/developer instructions used
      #
      #   @param max_output_tokens [Integer, nil] Maximum output tokens allowed for this response
      #
      #   @param max_tool_calls [Integer, nil] Maximum tool calls allowed for this response
      #
      #   @param mcp_server_errors [Hash{Symbol=>DedalusSDK::Models::Response::MCPServerError}, nil] MCP server failures keyed by server name.
      #
      #   @param mcp_tool_results [Array<DedalusSDK::Models::MCPToolResult>, nil] Results of MCP tool executions including inputs, outputs, and timing.
      #
      #   @param metadata [Hash{Symbol=>String}, nil] Key-value pairs attached to this response (requires BYOK)
      #
      #   @param object [Symbol, DedalusSDK::Models::Response::Object] The object type, always 'response'
      #
      #   @param output_text [String, nil] Aggregated text output from all output_text items (SDK-only convenience property
      #
      #   @param parallel_tool_calls [Boolean, nil] Whether parallel tool calls were enabled
      #
      #   @param presence_penalty [Float, nil] Presence penalty used for this response
      #
      #   @param previous_response_id [String, nil] Previous response ID referenced, if any
      #
      #   @param prompt_cache_key [String, nil] Prompt cache key used for this response
      #
      #   @param reasoning [Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}, nil] Reasoning configuration and outputs
      #
      #   @param safety_identifier [String, nil] Safety identifier used for this response
      #
      #   @param service_tier [String, nil] Service tier used for this response
      #
      #   @param store [Boolean, nil] Whether the response was stored for later retrieval
      #
      #   @param temperature [Float, nil] Temperature parameter used
      #
      #   @param text [Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}, nil] Text configuration used for this response
      #
      #   @param tool_choice [String, Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}, nil] Tool choice configuration used
      #
      #   @param tools [Array<Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}>, nil] Tools that were available to the model
      #
      #   @param tools_executed [Array<String>, nil] List of tool names that were executed server-side (e.g., MCP tools).
      #
      #   @param top_logprobs [Integer, nil] Number of logprob tokens returned per position
      #
      #   @param top_p [Float, nil] Top-p parameter used
      #
      #   @param truncation [String, nil] Truncation strategy applied when context exceeded limits
      #
      #   @param usage [Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}, nil] Token usage statistics for the response

      # The status of the response generation
      #
      # @see DedalusSDK::Models::Response#status
      module Status
        extend DedalusSDK::Internal::Type::Enum

        COMPLETED = :completed
        FAILED = :failed
        IN_PROGRESS = :in_progress
        CANCELLED = :cancelled
        QUEUED = :queued
        INCOMPLETE = :incomplete

        # @!method self.values
        #   @return [Array<Symbol>]
      end

      # System/developer instructions used
      #
      # @see DedalusSDK::Models::Response#instructions
      module Instructions
        extend DedalusSDK::Internal::Type::Union

        variant String

        variant -> { DedalusSDK::Models::Response::Instructions::JSONObjectInputArray }

        # @!method self.variants
        #   @return [Array(String, Array<Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil}>)]

        # @type [DedalusSDK::Internal::Type::Converter]
        JSONObjectInputArray =
          DedalusSDK::Internal::Type::ArrayOf[-> {
            DedalusSDK::Internal::Type::HashOf[union: DedalusSDK::JSONValueInput, nil?: true]
          }]
      end

      class MCPServerError < DedalusSDK::Internal::Type::BaseModel
        # @!attribute message
        #   Human-readable error message.
        #
        #   @return [String]
        required :message, String

        # @!attribute code
        #   Machine-readable error code.
        #
        #   @return [String, nil]
        optional :code, String, nil?: true

        # @!attribute recommendation
        #   Suggested action for the user.
        #
        #   @return [String, nil]
        optional :recommendation, String, nil?: true

        # @!method initialize(message:, code: nil, recommendation: nil)
        #   Error details for a single MCP server failure.
        #
        #   @param message [String] Human-readable error message.
        #
        #   @param code [String, nil] Machine-readable error code.
        #
        #   @param recommendation [String, nil] Suggested action for the user.
      end

      # The object type, always 'response'
      #
      # @see DedalusSDK::Models::Response#object
      module Object
        extend DedalusSDK::Internal::Type::Enum

        RESPONSE = :response

        # @!method self.values
        #   @return [Array<Symbol>]
      end

      # Tool choice configuration used
      #
      # @see DedalusSDK::Models::Response#tool_choice
      module ToolChoice
        extend DedalusSDK::Internal::Type::Union

        variant String

        variant -> { DedalusSDK::JSONObjectInput }

        # @!method self.variants
        #   @return [Array(String, Hash{Symbol=>String, Float, Boolean, Hash{Symbol=>DedalusSDK::Models::JSONValueInput, nil}, Array<DedalusSDK::Models::JSONValueInput, nil>, nil})]
      end
    end
  end
end
